"""
Playwright TypeScript renderer — Automation Generation Contract -> multi-file
bundle (spec + page objects + fixture). Every mapping here is total and
deterministic: the same contract always renders the same files. Step actions
come from a closed vocabulary (see StepAction in generation_contract.py) —
there is no free-text-to-code guessing; "custom" steps render as a visible
TODO comment rather than a fabricated call.
"""
from __future__ import annotations

import json
import re

from app.agents.automation.generation_contract import (
    ApiValidation,
    AutomationGenerationContract,
    CleanupAction,
    ContractAssertion,
    ContractStep,
    PageObject,
)
from app.services.script_compiler import data_bindings, locator_policy
from app.services.script_compiler.naming import env_var_name, js_string_literal

# Mirrors the standard JS `escapeRegExp` idiom
# (str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')). wait_for_url/url-assertion
# values are real captured URL fragments (e.g. "/sign-up?role=candidate"),
# not hand-written regexes — every one of these characters is common in a
# real query string or path, and passing it unescaped into `new RegExp(...)`
# silently reinterprets it as regex syntax instead of literal text (e.g. the
# '?' after "up" makes the preceding 'p' optional rather than matching a
# literal '?'). Confirmed via a live run: the page navigated to EXACTLY the
# target URL and the wait still timed out, because the compiled regex could
# no longer match it.
_JS_REGEX_SPECIAL_CHARS = re.compile(r"[.*+?^${}()|[\]\\]")


def _escape_regex_literal(value: str) -> str:
    return _JS_REGEX_SPECIAL_CHARS.sub(lambda m: "\\" + m.group(0), value)

GENERATION_HEADER_TEMPLATE = """/**
 * GENERATED BY nxtQA Script Compiler — DO NOT EDIT DIRECTLY
 * Contract Version: {contract_version}
 * Compiler Version: {compiler_version}
 * Test Case: {test_case_id}
 * Requirement: {requirement_id}
 * Environment Profile: {environment_profile}
 * Script Type: {script_type}
 */
"""


def _page_var_name(page_object_name: str) -> str:
    return (page_object_name[0].lower() + page_object_name[1:]) if page_object_name else "page"


def _resolve_target(target: str | None, page_var_map: dict[str, str]) -> str:
    if not target or target == "page":
        return "page"
    if "." in target:
        page_name, element = target.split(".", 1)
        var = page_var_map.get(page_name, _page_var_name(page_name))
        return f"{var}.{element}"
    return target


def render_page_object(page_object: PageObject) -> str:
    lines = [
        "import { Page, Locator } from '@playwright/test';",
        "",
        f"export class {page_object.name} {{",
        "  readonly page: Page;",
    ]
    for el in page_object.elements:
        lines.append(f"  readonly {el.name}: Locator;")
    lines.append("")
    lines.append("  constructor(page: Page) {")
    lines.append("    this.page = page;")
    for el in page_object.elements:
        locator_expr = locator_policy.render_locator_playwright(
            el.locator_strategy, el.locator_value, el.role_hint, el.nth
        )
        lines.append(f"    this.{el.name} = {locator_expr};")
    lines.append("  }")
    if page_object.route:
        lines.append("")
        lines.append("  async goto(): Promise<void> {")
        lines.append(f"    await this.page.goto({js_string_literal(page_object.route)});")
        lines.append("  }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _render_fixture_interface(tree: data_bindings.BindingTree, depth: int) -> list[str]:
    pad = "  " * depth
    lines: list[str] = []
    for name, child in tree.items():
        key = data_bindings.key_literal(name)
        if data_bindings.is_leaf(child):
            lines.append(f"{pad}{key}: string;")
        else:
            lines.append(f"{pad}{key}: {{")
            lines.extend(_render_fixture_interface(child, depth + 1))
            lines.append(f"{pad}}};")
    return lines


def _render_fixture_value(
    tree: data_bindings.BindingTree,
    fallbacks: dict[str, str],
    depth: int,
    prefix: str = "",
) -> list[str]:
    pad = "  " * depth
    lines: list[str] = []
    for name, child in tree.items():
        key = data_bindings.key_literal(name)
        path = f"{prefix}.{name}" if prefix else name
        if data_bindings.is_leaf(child):
            fallback = fallbacks.get(path)
            literal = js_string_literal(fallback) if fallback else "''"
            lines.append(f"{pad}{key}: process.env.{env_var_name(path)} ?? {literal},")
        else:
            lines.append(f"{pad}{key}: {{")
            lines.extend(_render_fixture_value(child, fallbacks, depth + 1, path))
            lines.append(f"{pad}}},")
    return lines


def render_fixture(contract: AutomationGenerationContract) -> str:
    """Declare the fixture in the shape the spec dereferences.

    Bindings are dotted paths (`validOtherFields.firstName`), so a binding with
    children has to render as a nested object — see data_bindings.py for what a
    flat `string` per declared binding used to produce at runtime.
    """
    tree = data_bindings.binding_tree(contract)
    fallbacks = {b.name: b.fallback for b in contract.test_data_bindings if b.fallback}

    lines = [
        "/** Test data bound from the platform's Test Data module — never a",
        " * hardcoded literal. See app/services/parameter_binding.py. */",
        "export interface TestDataFixture {",
    ]
    lines.extend(_render_fixture_interface(tree, 1))
    lines.append("}")
    lines.append("")
    lines.append("export const TEST_DATA: TestDataFixture = {")
    lines.extend(_render_fixture_value(tree, fallbacks, 1))
    lines.append("};")
    return "\n".join(lines) + "\n"


def _render_step_line(step: ContractStep, page_var_map: dict[str, str]) -> str:
    target_expr = _resolve_target(step.target, page_var_map)
    value_expr = (
        f"TEST_DATA.{step.data_binding}" if step.data_binding
        else (js_string_literal(step.value) if step.value is not None else "''")
    )

    if step.action == "navigate":
        path = step.value or step.target or "/"
        return f"await page.goto({js_string_literal(path)});"
    if step.action == "fill":
        return f"await {target_expr}.fill({value_expr});"
    if step.action == "click":
        return f"await {target_expr}.click();"
    if step.action == "check":
        return f"await {target_expr}.check();"
    if step.action == "uncheck":
        return f"await {target_expr}.uncheck();"
    if step.action == "select":
        return f"await {target_expr}.selectOption({value_expr});"
    if step.action == "hover":
        return f"await {target_expr}.hover();"
    if step.action == "wait_for_visible":
        return f"await expect({target_expr}).toBeVisible();"
    if step.action == "wait_for_url":
        pattern = step.value or ""
        # A raw `/{pattern}/` regex literal breaks on any pattern containing
        # an unescaped "/" — which every http(s):// URL does, since "//"
        # inside the delimiters prematurely closes the literal (confirmed
        # via a live run that failed with invalid syntax). new RegExp(...)
        # over a properly JS-string-escaped value has no delimiter to collide.
        # The pattern itself is escaped first (see _escape_regex_literal) —
        # it's a literal captured URL fragment, not a hand-written regex.
        return f"await page.waitForURL(new RegExp({js_string_literal(_escape_regex_literal(pattern))}));"
    if step.action == "custom":
        return f"// TODO: {step.description or 'custom step not auto-rendered — implement manually'}"
    raise ValueError(f"Unhandled step action: {step.action}")


def _render_assertion_line(a: ContractAssertion, page_var_map: dict[str, str]) -> str:
    target_expr = _resolve_target(a.target, page_var_map)
    if a.type == "visible":
        return f"await expect({target_expr}).toBeVisible();"
    if a.type == "text":
        return f"await expect({target_expr}).toContainText({js_string_literal(a.expected)});"
    if a.type == "url":
        # Same delimiter-collision bug as wait_for_url above — a bare
        # `/{a.expected}/` regex literal breaks on any URL containing "//".
        # Same regex-metachar escaping too — a.expected is a literal
        # captured URL fragment, not a hand-written regex.
        return f"await expect(page).toHaveURL(new RegExp({js_string_literal(_escape_regex_literal(a.expected))}));"
    if a.type == "value":
        return f"await expect({target_expr}).toHaveValue({js_string_literal(a.expected)});"
    if a.type == "count":
        return f"await expect({target_expr}).toHaveCount({a.expected});"
    raise ValueError(f"Unhandled assertion type: {a.type}")


# An expected_fields key is rendered as a JS property path, so it has to *be*
# one. Anything else (a bracket expression, a call, a quote) would either emit
# broken TypeScript or splice caller-controlled text into the generated test.
_JS_PROPERTY_PATH_RE = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*(\.[A-Za-z_$][A-Za-z0-9_$]*)*$")


def _render_api_validation_lines(v: ApiValidation, index: int) -> list[str]:
    var_name = f"apiResult{index}"
    options = [f"method: {js_string_literal(v.method)}", f"expectedStatus: {v.expected_status}"]
    lines = [
        f"const {var_name} = await requestJson("
        f"{js_string_literal(v.path)}, BASE_URL, {{ {', '.join(options)} }});",
        # requestJson already throws on a mismatch; asserting it again makes the
        # declared status visible in the report as its own expectation rather
        # than only as a thrown error.
        f"expect({var_name}.status).toBe({v.expected_status});",
    ]
    for field, expected in v.expected_fields.items():
        if not _JS_PROPERTY_PATH_RE.match(field or ""):
            raise ValueError(
                f"API validation for {v.path!r} declares expected field {field!r}, which is "
                "not a valid property path. Use dotted identifiers such as 'data.orderId'."
            )
        lines.append(f"expect({var_name}.body.{field}).toBe({js_string_literal(expected)});")
    return lines


def _render_db_validation_lines(v: DbValidation = None, *, db_validation=None) -> list[str]:
    validation = db_validation or v
    query_json = json.dumps(validation.query)
    # expect_found=false previously still rendered assertRowExists with a TODO,
    # asserting the exact opposite of the contract (AUT-005).
    helper = "assertRowExists" if validation.expect_found else "assertRowAbsent"
    return [f"await {helper}(DB_VALIDATION_ENDPOINT, {query_json});"]


def _has_api_cleanup(contract: AutomationGenerationContract) -> bool:
    """Whether any cleanup action renders a getJson call.

    These need apiClient.ts and BASE_URL just as apiValidations do. Before this
    the import and the constant were gated on api_validations alone, so a
    contract with only an api_call cleanup compiled to a spec referencing an
    undefined helper and an absent bundle file.
    """
    return any(c.type == "api_call" and c.target for c in contract.cleanup_actions)


def _render_cleanup_line(c: CleanupAction) -> str:
    if c.type == "api_call" and c.target:
        return f"await getJson({js_string_literal(c.target)}, BASE_URL);  // {c.description}"
    return f"// Cleanup: {c.description}"


def render_spec(contract: AutomationGenerationContract, *, compiler_version: str) -> str:
    page_var_map = {po.name: _page_var_name(po.name) for po in contract.page_objects}

    needs_api_client = bool(contract.api_validations)
    needs_db_validator = bool(contract.db_validations)
    needs_evidence_helper = bool(contract.evidence_required)
    needs_fixture = bool(contract.test_data_bindings)

    imports = ["import { test, expect } from '@playwright/test';"]
    for po in contract.page_objects:
        imports.append(f"import {{ {po.name} }} from '../pages/{po.name}';")
    if needs_fixture:
        imports.append("import { TEST_DATA } from '../fixtures/testData.fixture';")
    if needs_api_client or _has_api_cleanup(contract):
        api_imports = ["getJson"] if _has_api_cleanup(contract) else []
        if needs_api_client:
            api_imports.insert(0, "requestJson")
        imports.append(
            f"import {{ {', '.join(api_imports)} }} from '../utils/apiClient';"
        )
    if needs_db_validator:
        db_helpers = sorted(
            {
                "assertRowExists" if v.expect_found else "assertRowAbsent"
                for v in contract.db_validations
            }
        )
        imports.append(f"import {{ {', '.join(db_helpers)} }} from '../utils/dbValidator';")
    if needs_evidence_helper:
        imports.append(
            "import { declareRequiredEvidence } from '../utils/evidenceHelper';"
        )

    preamble: list[str] = []
    if needs_api_client or needs_db_validator or _has_api_cleanup(contract):
        preamble.append("const BASE_URL = process.env.BASE_URL ?? '';")
    if needs_db_validator:
        preamble.append("const DB_VALIDATION_ENDPOINT = process.env.DB_VALIDATION_ENDPOINT ?? '';")
    if preamble:
        preamble.append("")

    # Console/network capture (Phase 4.2) — always on, via beforeEach/afterEach
    # so the attachment is written even when the test throws partway through;
    # inline code at the end of the test body would never run on failure.
    preamble.append("let consoleLogs: Array<{ type: string; text: string }> = [];")
    preamble.append("let networkLogs: Array<{ url: string; status: number; method: string }> = [];")
    preamble.append("")
    preamble.append("test.beforeEach(async ({ page }) => {")
    preamble.append("  consoleLogs = [];")
    preamble.append("  networkLogs = [];")
    preamble.append("  page.on('console', (msg) => consoleLogs.push({ type: msg.type(), text: msg.text() }));")
    preamble.append(
        "  page.on('response', (response) => "
        "networkLogs.push({ url: response.url(), status: response.status(), method: response.request().method() }));"
    )
    preamble.append("});")
    preamble.append("")
    preamble.append("test.afterEach(async ({}, testInfo) => {")
    preamble.append("  await testInfo.attach('console-logs.json', { body: JSON.stringify(consoleLogs), contentType: 'application/json' });")
    preamble.append("  await testInfo.attach('network-logs.json', { body: JSON.stringify(networkLogs), contentType: 'application/json' });")
    preamble.append("});")
    preamble.append("")

    test_params = "{ page }, testInfo" if needs_evidence_helper else "{ page }"
    body: list[str] = []
    body.append(f"test.describe({js_string_literal(f'{contract.test_case_id} — {contract.business_flow}')}, () => {{")
    body.append(f"  test({js_string_literal(contract.business_flow or contract.test_case_id)}, async ({test_params}) => {{")

    for po in contract.page_objects:
        body.append(f"    const {page_var_map[po.name]} = new {po.name}(page);")
    if contract.page_objects:
        body.append("")

    arrange_steps = [s for s in contract.steps if s.phase == "arrange"]
    act_steps = [s for s in contract.steps if s.phase == "act"]
    assert_steps = [s for s in contract.steps if s.phase == "assert"]

    body.append("    // Arrange")
    for step in arrange_steps:
        body.append(f"    {_render_step_line(step, page_var_map)}")
    if not arrange_steps:
        body.append("    // (no arrange steps in the contract)")
    body.append("")

    body.append("    // Act")
    for step in act_steps:
        body.append(f"    {_render_step_line(step, page_var_map)}")
    if not act_steps:
        body.append("    // (no act steps in the contract)")
    body.append("")

    body.append("    // Assert")
    has_any_assertion = bool(assert_steps or contract.assertions or contract.api_validations or contract.db_validations)
    for step in assert_steps:
        body.append(f"    {_render_step_line(step, page_var_map)}")
    for a in contract.assertions:
        body.append(f"    {_render_assertion_line(a, page_var_map)}")
    for i, v in enumerate(contract.api_validations, start=1):
        for line in _render_api_validation_lines(v, i):
            body.append(f"    {line}")
    for v in contract.db_validations:
        for line in _render_db_validation_lines(db_validation=v):
            body.append(f"    {line}")
    if not has_any_assertion:
        body.append("    // (no assertions in the contract)")
    body.append("")

    if needs_evidence_helper:
        # The contract carries evidence *names* with no value expression, so
        # there is nothing real to attach. Emitting attachEvidence(name, name)
        # produced an attachment that looked captured but only contained its own
        # label (AUT-005); these are recorded as outstanding requirements.
        body.append("    // Evidence (declared by the contract, not yet capturable)")
        for name in contract.evidence_required:
            body.append(
                f"    await declareRequiredEvidence(testInfo, {js_string_literal(name)});"
            )
        body.append("")

    body.append("    // Cleanup")
    if contract.cleanup_actions:
        for c in contract.cleanup_actions:
            body.append(f"    {_render_cleanup_line(c)}")
    else:
        body.append("    // (no cleanup actions declared in the contract)")

    body.append("  });")
    body.append("});")

    header = GENERATION_HEADER_TEMPLATE.format(
        contract_version=contract.contract_version,
        compiler_version=compiler_version,
        test_case_id=contract.test_case_id,
        requirement_id=contract.requirement_id or "n/a",
        environment_profile=contract.environment_profile,
        script_type=contract.script_type,
    )
    return header + "\n" + "\n".join(imports) + "\n\n" + "\n".join(preamble + body) + "\n"
