"""
Playwright TypeScript renderer — Automation Generation Contract -> multi-file
bundle (spec + page objects + fixture). Every mapping here is total and
deterministic: the same contract always renders the same files. Step actions
come from a closed vocabulary (see StepAction in generation_contract.py) —
there is no free-text-to-code guessing; "custom" steps render as a visible
TODO comment rather than a fabricated call.
"""
from __future__ import annotations

import json
import re

from app.agents.automation.generation_contract import (
    ApiValidation,
    AutomationGenerationContract,
    CleanupAction,
    ContractAssertion,
    ContractStep,
    PageObject,
)
from app.services.script_compiler import locator_policy
from app.services.script_compiler.naming import env_var_name, js_string_literal

# Mirrors the standard JS `escapeRegExp` idiom
# (str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')). wait_for_url/url-assertion
# values are real captured URL fragments (e.g. "/sign-up?role=candidate"),
# not hand-written regexes — every one of these characters is common in a
# real query string or path, and passing it unescaped into `new RegExp(...)`
# silently reinterprets it as regex syntax instead of literal text (e.g. the
# '?' after "up" makes the preceding 'p' optional rather than matching a
# literal '?'). Confirmed via a live run: the page navigated to EXACTLY the
# target URL and the wait still timed out, because the compiled regex could
# no longer match it.
_JS_REGEX_SPECIAL_CHARS = re.compile(r"[.*+?^${}()|[\]\\]")


def _escape_regex_literal(value: str) -> str:
    return _JS_REGEX_SPECIAL_CHARS.sub(lambda m: "\\" + m.group(0), value)

GENERATION_HEADER_TEMPLATE = """/**
 * GENERATED BY nxtQA Script Compiler — DO NOT EDIT DIRECTLY
 * Contract Version: {contract_version}
 * Compiler Version: {compiler_version}
 * Test Case: {test_case_id}
 * Requirement: {requirement_id}
 * Environment Profile: {environment_profile}
 * Script Type: {script_type}
 */
"""


def _page_var_name(page_object_name: str) -> str:
    return (page_object_name[0].lower() + page_object_name[1:]) if page_object_name else "page"


def _resolve_target(target: str | None, page_var_map: dict[str, str]) -> str:
    if not target or target == "page":
        return "page"
    if "." in target:
        page_name, element = target.split(".", 1)
        var = page_var_map.get(page_name, _page_var_name(page_name))
        return f"{var}.{element}"
    return target


def render_page_object(page_object: PageObject) -> str:
    lines = [
        "import { Page, Locator } from '@playwright/test';",
        "",
        f"export class {page_object.name} {{",
        "  readonly page: Page;",
    ]
    for el in page_object.elements:
        lines.append(f"  readonly {el.name}: Locator;")
    lines.append("")
    lines.append("  constructor(page: Page) {")
    lines.append("    this.page = page;")
    for el in page_object.elements:
        locator_expr = locator_policy.render_locator_playwright(
            el.locator_strategy, el.locator_value, el.role_hint, el.nth
        )
        lines.append(f"    this.{el.name} = {locator_expr};")
    lines.append("  }")
    if page_object.route:
        lines.append("")
        lines.append("  async goto(): Promise<void> {")
        lines.append(f"    await this.page.goto({js_string_literal(page_object.route)});")
        lines.append("  }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_fixture(contract: AutomationGenerationContract) -> str:
    lines = [
        "/** Test data bound from the platform's Test Data module — never a",
        " * hardcoded literal. See app/services/parameter_binding.py. */",
        "export interface TestDataFixture {",
    ]
    for binding in contract.test_data_bindings:
        lines.append(f"  {binding.name}: string;")
    lines.append("}")
    lines.append("")
    lines.append("export const TEST_DATA: TestDataFixture = {")
    for binding in contract.test_data_bindings:
        fallback = js_string_literal(binding.fallback) if binding.fallback else "''"
        lines.append(f"  {binding.name}: process.env.{env_var_name(binding.name)} ?? {fallback},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def _render_step_line(step: ContractStep, page_var_map: dict[str, str]) -> str:
    target_expr = _resolve_target(step.target, page_var_map)
    value_expr = (
        f"TEST_DATA.{step.data_binding}" if step.data_binding
        else (js_string_literal(step.value) if step.value is not None else "''")
    )

    if step.action == "navigate":
        path = step.value or step.target or "/"
        return f"await page.goto({js_string_literal(path)});"
    if step.action == "fill":
        return f"await {target_expr}.fill({value_expr});"
    if step.action == "click":
        return f"await {target_expr}.click();"
    if step.action == "check":
        return f"await {target_expr}.check();"
    if step.action == "uncheck":
        return f"await {target_expr}.uncheck();"
    if step.action == "select":
        return f"await {target_expr}.selectOption({value_expr});"
    if step.action == "hover":
        return f"await {target_expr}.hover();"
    if step.action == "wait_for_visible":
        return f"await expect({target_expr}).toBeVisible();"
    if step.action == "wait_for_url":
        pattern = step.value or ""
        # A raw `/{pattern}/` regex literal breaks on any pattern containing
        # an unescaped "/" — which every http(s):// URL does, since "//"
        # inside the delimiters prematurely closes the literal (confirmed
        # via a live run that failed with invalid syntax). new RegExp(...)
        # over a properly JS-string-escaped value has no delimiter to collide.
        # The pattern itself is escaped first (see _escape_regex_literal) —
        # it's a literal captured URL fragment, not a hand-written regex.
        return f"await page.waitForURL(new RegExp({js_string_literal(_escape_regex_literal(pattern))}));"
    if step.action == "custom":
        return f"// TODO: {step.description or 'custom step not auto-rendered — implement manually'}"
    raise ValueError(f"Unhandled step action: {step.action}")


def _render_assertion_line(a: ContractAssertion, page_var_map: dict[str, str]) -> str:
    target_expr = _resolve_target(a.target, page_var_map)
    if a.type == "visible":
        return f"await expect({target_expr}).toBeVisible();"
    if a.type == "text":
        return f"await expect({target_expr}).toContainText({js_string_literal(a.expected)});"
    if a.type == "url":
        # Same delimiter-collision bug as wait_for_url above — a bare
        # `/{a.expected}/` regex literal breaks on any URL containing "//".
        # Same regex-metachar escaping too — a.expected is a literal
        # captured URL fragment, not a hand-written regex.
        return f"await expect(page).toHaveURL(new RegExp({js_string_literal(_escape_regex_literal(a.expected))}));"
    if a.type == "value":
        return f"await expect({target_expr}).toHaveValue({js_string_literal(a.expected)});"
    if a.type == "count":
        return f"await expect({target_expr}).toHaveCount({a.expected});"
    raise ValueError(f"Unhandled assertion type: {a.type}")


def _render_api_validation_lines(v: ApiValidation, index: int) -> list[str]:
    var_name = f"apiResult{index}"
    lines = [f"const {var_name} = await getJson({js_string_literal(v.path)}, BASE_URL);"]
    for field, expected in v.expected_fields.items():
        lines.append(f"expect({var_name}.{field}).toBe({js_string_literal(expected)});")
    return lines


def _render_db_validation_lines(v: DbValidation = None, *, db_validation=None) -> list[str]:
    validation = db_validation or v
    query_json = json.dumps(validation.query)
    line = f"await assertRowExists(DB_VALIDATION_ENDPOINT, {query_json});"
    if not validation.expect_found:
        line += "  // TODO: expect_found=false is not yet rendered — verify absence manually"
    return [line]


def _render_cleanup_line(c: CleanupAction) -> str:
    if c.type == "api_call" and c.target:
        return f"await getJson({js_string_literal(c.target)}, BASE_URL);  // {c.description}"
    return f"// Cleanup: {c.description}"


def render_spec(contract: AutomationGenerationContract, *, compiler_version: str) -> str:
    page_var_map = {po.name: _page_var_name(po.name) for po in contract.page_objects}

    needs_api_client = bool(contract.api_validations)
    needs_db_validator = bool(contract.db_validations)
    needs_evidence_helper = bool(contract.evidence_required)
    needs_fixture = bool(contract.test_data_bindings)

    imports = ["import { test, expect } from '@playwright/test';"]
    for po in contract.page_objects:
        imports.append(f"import {{ {po.name} }} from '../pages/{po.name}';")
    if needs_fixture:
        imports.append("import { TEST_DATA } from '../fixtures/testData.fixture';")
    if needs_api_client:
        imports.append("import { getJson } from '../utils/apiClient';")
    if needs_db_validator:
        imports.append("import { assertRowExists } from '../utils/dbValidator';")
    if needs_evidence_helper:
        imports.append("import { attachEvidence } from '../utils/evidenceHelper';")

    preamble: list[str] = []
    if needs_api_client or needs_db_validator:
        preamble.append("const BASE_URL = process.env.BASE_URL ?? '';")
    if needs_db_validator:
        preamble.append("const DB_VALIDATION_ENDPOINT = process.env.DB_VALIDATION_ENDPOINT ?? '';")
    if preamble:
        preamble.append("")

    # Console/network capture (Phase 4.2) — always on, via beforeEach/afterEach
    # so the attachment is written even when the test throws partway through;
    # inline code at the end of the test body would never run on failure.
    preamble.append("let consoleLogs: Array<{ type: string; text: string }> = [];")
    preamble.append("let networkLogs: Array<{ url: string; status: number; method: string }> = [];")
    preamble.append("")
    preamble.append("test.beforeEach(async ({ page }) => {")
    preamble.append("  consoleLogs = [];")
    preamble.append("  networkLogs = [];")
    preamble.append("  page.on('console', (msg) => consoleLogs.push({ type: msg.type(), text: msg.text() }));")
    preamble.append(
        "  page.on('response', (response) => "
        "networkLogs.push({ url: response.url(), status: response.status(), method: response.request().method() }));"
    )
    preamble.append("});")
    preamble.append("")
    preamble.append("test.afterEach(async ({}, testInfo) => {")
    preamble.append("  await testInfo.attach('console-logs.json', { body: JSON.stringify(consoleLogs), contentType: 'application/json' });")
    preamble.append("  await testInfo.attach('network-logs.json', { body: JSON.stringify(networkLogs), contentType: 'application/json' });")
    preamble.append("});")
    preamble.append("")

    test_params = "{ page }, testInfo" if needs_evidence_helper else "{ page }"
    body: list[str] = []
    body.append(f"test.describe({js_string_literal(f'{contract.test_case_id} — {contract.business_flow}')}, () => {{")
    body.append(f"  test({js_string_literal(contract.business_flow or contract.test_case_id)}, async ({test_params}) => {{")

    for po in contract.page_objects:
        body.append(f"    const {page_var_map[po.name]} = new {po.name}(page);")
    if contract.page_objects:
        body.append("")

    arrange_steps = [s for s in contract.steps if s.phase == "arrange"]
    act_steps = [s for s in contract.steps if s.phase == "act"]
    assert_steps = [s for s in contract.steps if s.phase == "assert"]

    body.append("    // Arrange")
    for step in arrange_steps:
        body.append(f"    {_render_step_line(step, page_var_map)}")
    if not arrange_steps:
        body.append("    // (no arrange steps in the contract)")
    body.append("")

    body.append("    // Act")
    for step in act_steps:
        body.append(f"    {_render_step_line(step, page_var_map)}")
    if not act_steps:
        body.append("    // (no act steps in the contract)")
    body.append("")

    body.append("    // Assert")
    has_any_assertion = bool(assert_steps or contract.assertions or contract.api_validations or contract.db_validations)
    for step in assert_steps:
        body.append(f"    {_render_step_line(step, page_var_map)}")
    for a in contract.assertions:
        body.append(f"    {_render_assertion_line(a, page_var_map)}")
    for i, v in enumerate(contract.api_validations, start=1):
        for line in _render_api_validation_lines(v, i):
            body.append(f"    {line}")
    for v in contract.db_validations:
        for line in _render_db_validation_lines(db_validation=v):
            body.append(f"    {line}")
    if not has_any_assertion:
        body.append("    // (no assertions in the contract)")
    body.append("")

    if needs_evidence_helper:
        body.append("    // Evidence")
        for name in contract.evidence_required:
            body.append(
                f"    await attachEvidence(testInfo, {js_string_literal(name)}, {js_string_literal(name)});"
            )
        body.append("")

    body.append("    // Cleanup")
    if contract.cleanup_actions:
        for c in contract.cleanup_actions:
            body.append(f"    {_render_cleanup_line(c)}")
    else:
        body.append("    // (no cleanup actions declared in the contract)")

    body.append("  });")
    body.append("});")

    header = GENERATION_HEADER_TEMPLATE.format(
        contract_version=contract.contract_version,
        compiler_version=compiler_version,
        test_case_id=contract.test_case_id,
        requirement_id=contract.requirement_id or "n/a",
        environment_profile=contract.environment_profile,
        script_type=contract.script_type,
    )
    return header + "\n" + "\n".join(imports) + "\n\n" + "\n".join(preamble + body) + "\n"
