"""
Pytest renderer — Automation Generation Contract -> a single deterministic
test module. Simpler than the Playwright TS renderer (no separate page-object
files) but follows the same rules: closed step-action vocabulary, no inline
test data literals, Arrange-Act-Assert-Evidence-Cleanup structure.
"""
from __future__ import annotations

import json
import re

from app.agents.automation.generation_contract import (
    ApiValidation,
    AutomationGenerationContract,
    CleanupAction,
    ContractAssertion,
    ContractStep,
)
from app.services.script_compiler import locator_policy
from app.services.script_compiler.naming import env_var_name, py_string_literal

GENERATION_HEADER_TEMPLATE = """# GENERATED BY nxtQA Script Compiler — DO NOT EDIT DIRECTLY
# Contract Version: {contract_version}
# Compiler Version: {compiler_version}
# Test Case: {test_case_id}
# Requirement: {requirement_id}
# Environment Profile: {environment_profile}
# Script Type: {script_type}
\"\"\"{test_case_id} — {business_flow}\"\"\"
"""


def _resolve_target(target: str | None) -> str:
    if not target or target == "page":
        return "page"
    if "." in target:
        _page, element = target.split(".", 1)
        return f"page.{element}"
    return target


def _render_step_line(step: ContractStep) -> str:
    target_expr = _resolve_target(step.target)
    value_expr = (
        f"test_data['{step.data_binding}']" if step.data_binding
        else (py_string_literal(step.value) if step.value is not None else '""')
    )

    if step.action == "navigate":
        path = step.value or step.target or "/"
        return f"page.goto({py_string_literal(path)})"
    if step.action == "fill":
        return f"{target_expr}.fill({value_expr})"
    if step.action == "click":
        return f"{target_expr}.click()"
    if step.action == "check":
        return f"{target_expr}.check()"
    if step.action == "uncheck":
        return f"{target_expr}.uncheck()"
    if step.action == "select":
        return f"{target_expr}.select_option({value_expr})"
    if step.action == "hover":
        return f"{target_expr}.hover()"
    if step.action == "wait_for_visible":
        return f"expect({target_expr}).to_be_visible()"
    if step.action == "wait_for_url":
        pattern = step.value or ""
        # pattern is a literal captured URL fragment (e.g.
        # "/sign-up?role=candidate"), not a hand-written regex — re.escape
        # here (compiler-side, at generation time) bakes an escaped literal
        # into the generated file's re.compile(...) call. Without this the
        # generated test's OWN re.compile() reinterprets '?'/'.' etc. as
        # regex syntax instead of literal characters (same class of bug
        # fixed in playwright_renderer._escape_regex_literal).
        return f"page.wait_for_url(re.compile({py_string_literal(re.escape(pattern))}))"
    if step.action == "custom":
        return f"# TODO: {step.description or 'custom step not auto-rendered — implement manually'}"
    raise ValueError(f"Unhandled step action: {step.action}")


def _render_assertion_line(a: ContractAssertion) -> str:
    target_expr = _resolve_target(a.target)
    if a.type == "visible":
        return f"expect({target_expr}).to_be_visible()"
    if a.type == "text":
        return f"expect({target_expr}).to_contain_text({py_string_literal(a.expected)})"
    if a.type == "url":
        # Same escaping requirement as wait_for_url above.
        return f"expect(page).to_have_url(re.compile({py_string_literal(re.escape(a.expected))}))"
    if a.type == "value":
        return f"expect({target_expr}).to_have_value({py_string_literal(a.expected)})"
    if a.type == "count":
        return f"expect({target_expr}).to_have_count({a.expected})"
    raise ValueError(f"Unhandled assertion type: {a.type}")


def _render_api_validation_lines(v: ApiValidation, index: int) -> list[str]:
    var_name = f"api_result_{index}"
    method = v.method.lower()
    lines = [f"{var_name} = httpx.{method}(f\"{{BASE_URL}}{v.path}\", timeout=30)"]
    lines.append(f"assert {var_name}.status_code == {v.expected_status}")
    if v.expected_fields:
        lines.append(f"{var_name}_body = {var_name}.json()")
        for field, expected in v.expected_fields.items():
            # The key goes through the literal renderer rather than being
            # spliced between raw quotes, so a field name containing a quote
            # cannot break out of the subscript.
            lines.append(
                f"assert {var_name}_body[{py_string_literal(field)}] == {py_string_literal(expected)}"
            )
    return lines


def _render_db_validation_lines(v) -> list[str]:
    query_json = json.dumps(v.query)
    # expect_found=False previously still rendered assert_row_exists with a
    # TODO, asserting the exact opposite of the contract (AUT-005).
    helper = "assert_row_exists" if v.expect_found else "assert_row_absent"
    return [f"{helper}(DB_VALIDATION_ENDPOINT, {query_json})"]


def _render_cleanup_line(c: CleanupAction) -> str:
    if c.type == "api_call" and c.target:
        return f"httpx.post(f\"{{BASE_URL}}{c.target}\", timeout=30)  # {c.description}"
    return f"# Cleanup: {c.description}"


def render_test_module(contract: AutomationGenerationContract, *, compiler_version: str) -> str:
    needs_api_client = bool(contract.api_validations)
    needs_db_validator = bool(contract.db_validations)
    needs_regex = any(s.action == "wait_for_url" for s in contract.steps) or any(
        a.type == "url" for a in contract.assertions
    )
    needs_playwright = any(
        s.action in ("fill", "click", "check", "uncheck", "select", "hover", "wait_for_visible")
        for s in contract.steps
    ) or any(a.type in ("visible", "text", "value", "count") for a in contract.assertions)

    imports = ["import os"]
    if needs_regex:
        imports.append("import re")
    imports.append("")
    imports.append("import httpx")
    imports.append("import pytest")
    if needs_playwright:
        imports.append("from playwright.sync_api import expect")
    if needs_db_validator:
        # Sibling module materialized flat alongside this file in the
        # automation workspace (see automation_runner/workspace.py) —
        # pytest's rootdir-based collection resolves it without a package.
        db_helpers = sorted(
            {
                "assert_row_exists" if v.expect_found else "assert_row_absent"
                for v in contract.db_validations
            }
        )
        imports.append(f"from db_validator import {', '.join(db_helpers)}")

    preamble: list[str] = []
    if needs_api_client or needs_db_validator:
        preamble.append('BASE_URL = os.environ["BASE_URL"]')
    if needs_db_validator:
        preamble.append('DB_VALIDATION_ENDPOINT = os.environ["DB_VALIDATION_ENDPOINT"]')

    fixture_lines: list[str] = []
    if contract.test_data_bindings:
        fixture_lines.append("@pytest.fixture")
        fixture_lines.append("def test_data():")
        fixture_lines.append("    # Test data bound from the platform's Test Data module —")
        fixture_lines.append("    # never a hardcoded literal. See app/services/parameter_binding.py.")
        fixture_lines.append("    return {")
        for binding in contract.test_data_bindings:
            fallback = py_string_literal(binding.fallback) if binding.fallback else '""'
            fixture_lines.append(f'        "{binding.name}": os.environ.get("{env_var_name(binding.name)}", {fallback}),')
        fixture_lines.append("    }")
        fixture_lines.append("")

    test_data_arg = "test_data" if contract.test_data_bindings else ""
    page_arg = "page" if needs_playwright else ""
    args = ", ".join(a for a in (page_arg, test_data_arg) if a)
    func_name = "test_" + contract.test_case_id.lower().replace("-", "_")

    body: list[str] = []
    body.append(f"def {func_name}({args}):")

    arrange_steps = [s for s in contract.steps if s.phase == "arrange"]
    act_steps = [s for s in contract.steps if s.phase == "act"]
    assert_steps = [s for s in contract.steps if s.phase == "assert"]

    body.append("    # Arrange")
    for step in arrange_steps:
        body.append(f"    {_render_step_line(step)}")
    if not arrange_steps:
        body.append("    # (no arrange steps in the contract)")
    body.append("")

    body.append("    # Act")
    for step in act_steps:
        body.append(f"    {_render_step_line(step)}")
    if not act_steps:
        body.append("    # (no act steps in the contract)")
    body.append("")

    body.append("    # Assert")
    has_any_assertion = bool(assert_steps or contract.assertions or contract.api_validations or contract.db_validations)
    for step in assert_steps:
        body.append(f"    {_render_step_line(step)}")
    for a in contract.assertions:
        body.append(f"    {_render_assertion_line(a)}")
    for i, v in enumerate(contract.api_validations, start=1):
        for line in _render_api_validation_lines(v, i):
            body.append(f"    {line}")
    for v in contract.db_validations:
        for line in _render_db_validation_lines(v):
            body.append(f"    {line}")
    if not has_any_assertion:
        body.append("    # (no assertions in the contract)")
    body.append("")

    if contract.evidence_required:
        # Printing "=captured" claimed a capture that never happened — the
        # pytest sibling of the attachEvidence(name, name) defect (AUT-005).
        # The requirement is recorded as outstanding instead.
        body.append("    # Evidence (declared by the contract, not yet capturable)")
        for name in contract.evidence_required:
            body.append(
                f'    print("evidence:{name}=not_captured "'
                f' "(declared by the contract; no value binding available)")'
            )
        body.append("")

    body.append("    # Cleanup")
    if contract.cleanup_actions:
        for c in contract.cleanup_actions:
            body.append(f"    {_render_cleanup_line(c)}")
    else:
        body.append("    # (no cleanup actions declared in the contract)")

    header = GENERATION_HEADER_TEMPLATE.format(
        contract_version=contract.contract_version,
        compiler_version=compiler_version,
        test_case_id=contract.test_case_id,
        requirement_id=contract.requirement_id or "n/a",
        environment_profile=contract.environment_profile,
        script_type=contract.script_type,
        business_flow=contract.business_flow or contract.test_case_id,
    )
    sections = [header, "\n".join(imports)]
    if preamble:
        sections.append("\n".join(preamble))
    if fixture_lines:
        sections.append("\n".join(fixture_lines))
    sections.append("\n".join(body))
    return "\n\n".join(sections) + "\n"
