/**
 * GENERATED BY nxtQA Script Compiler — DO NOT EDIT DIRECTLY
 * Contract Version: 1.0
 * Compiler Version: 1.0.0
 * Test Case: TC-0001
 * Requirement: REQ-0001
 * Environment Profile: QA
 * Script Type: playwright-typescript
 */
import { test, expect } from '@playwright/test';
import { LoginPage } from '../pages/LoginPage';
import { VALID_USER } from '../fixtures/users.fixture';
import { attachEvidence } from '../utils/evidenceHelper';

test.describe('TC-0001 — Valid login succeeds', () => {
  test('user logs in with valid credentials and reaches the dashboard', async ({ page }, testInfo) => {
    const loginPage = new LoginPage(page);

    // Arrange
    await loginPage.goto();

    // Act
    await loginPage.login(VALID_USER.username, VALID_USER.password);

    // Assert
    await expect(page).toHaveURL(/\/dashboard/);
    await expect(page.getByRole('heading', { name: 'Dashboard' })).toBeVisible();

    // Evidence
    await attachEvidence(testInfo, 'logged-in-user', VALID_USER.username);

    // Cleanup — session ends with the browser context; nothing to reverse.
  });
});
