/**
 * GENERATED BY nxtQA Script Compiler — DO NOT EDIT DIRECTLY
 * Contract Version: 1.0
 * Compiler Version: 1.0.0
 * Test Case: TC-0002
 * Requirement: REQ-0001
 * Environment Profile: QA
 * Script Type: playwright-typescript
 */
import { test, expect } from '@playwright/test';
import { LoginPage } from '../pages/LoginPage';
import { INVALID_USER } from '../fixtures/users.fixture';

test.describe('TC-0002 — Invalid credentials are rejected', () => {
  test('user sees an error and is not redirected on invalid password', async ({ page }) => {
    const loginPage = new LoginPage(page);

    // Arrange
    await loginPage.goto();

    // Act
    await loginPage.login(INVALID_USER.username, INVALID_USER.password);

    // Assert
    await loginPage.expectLoginError('Invalid username or password');
    await expect(page).toHaveURL(/\/login/);

    // Cleanup — no state was created on an invalid login attempt.
  });
});
