/**
 * GENERATED BY nxtQA Script Compiler — DO NOT EDIT DIRECTLY
 * Contract Version: 1.0
 * Compiler Version: 1.0.0
 * Test Case: TC-0004
 * Requirement: REQ-0010
 * Environment Profile: SIT
 * Script Type: playwright-typescript
 */
import { test, expect } from '@playwright/test';
import { LoginPage } from '../pages/LoginPage';
import { OrderPage } from '../pages/OrderPage';
import { VALID_USER } from '../fixtures/users.fixture';
import { getJson } from '../utils/apiClient';
import { assertRowExists } from '../utils/dbValidator';
import { attachEvidence } from '../utils/evidenceHelper';

const BASE_URL = process.env.BASE_URL ?? '';
const DB_VALIDATION_ENDPOINT = process.env.DB_VALIDATION_ENDPOINT ?? '';

test.describe('TC-0004 — Order creation is confirmed end-to-end', () => {
  test('order created via UI is verifiable through the API and the ledger', async ({ page }, testInfo) => {
    const loginPage = new LoginPage(page);
    const orderPage = new OrderPage(page);

    // Arrange
    await loginPage.goto();
    await loginPage.login(VALID_USER.username, VALID_USER.password);
    await orderPage.goto();

    // Act
    await orderPage.createOrder('Enterprise Data Plan');
    const orderId = await orderPage.expectOrderConfirmed();

    // Assert — UI confirmation
    expect(orderId).not.toBe('');

    // Assert — API validation: SIT requires interface-level confirmation,
    // not just the UI's word for it.
    const order = await getJson(`/api/orders/${orderId}`, BASE_URL);
    expect(order.status).toBe('created');

    // Assert — DB validation: the billing ledger must have a matching entry.
    await assertRowExists(DB_VALIDATION_ENDPOINT, { table: 'billing_ledger', order_id: orderId });

    // Evidence
    await attachEvidence(testInfo, 'created-order-id', orderId);

    // Cleanup — mark the order cancelled via API so it doesn't pollute
    // downstream regression data.
    await getJson(`/api/orders/${orderId}/cancel`, BASE_URL);
  });
});
