/**
 * GENERATED BY nxtQA Script Compiler — DO NOT EDIT DIRECTLY
 * Contract Version: 1.0
 * Compiler Version: 1.0.0
 * Test Case: TC-0005
 * Requirement: REQ-0001
 * Environment Profile: PROD_SANITY
 * Script Type: playwright-typescript
 */
import { test, expect } from '@playwright/test';

// PROD_SANITY compiles to non-invasive, read-only checks only — no login
// with real credentials, no state-changing actions. This is the minimal
// critical-path smoke check confirming the feature is alive in production.
test.describe('TC-0005 — Login page is reachable in production', () => {
  test('the login page renders its core elements', async ({ page }) => {
    // Arrange / Act
    await page.goto('/login');

    // Assert — read-only presence checks only.
    await expect(page.getByLabel('Username')).toBeVisible();
    await expect(page.getByLabel('Password')).toBeVisible();
    await expect(page.getByRole('button', { name: 'Sign in' })).toBeVisible();

    // Cleanup — nothing to reverse; no state was created.
  });
});
