/**
 * GENERATED BY nxtQA Script Compiler — DO NOT EDIT DIRECTLY
 * Contract Version: 1.0
 * Compiler Version: 1.0.0
 * Test Case: TC-0003
 * Requirement: REQ-0002
 * Environment Profile: SIT
 * Script Type: playwright-typescript
 */
import { test, expect } from '@playwright/test';
import { LoginPage } from '../pages/LoginPage';
import { VALID_USER } from '../fixtures/users.fixture';

test.describe('TC-0003 — Standard user cannot access the admin console', () => {
  test('navigating to /admin as a standard-role user is denied', async ({ page }) => {
    const loginPage = new LoginPage(page);

    // Arrange
    await loginPage.goto();
    await loginPage.login(VALID_USER.username, VALID_USER.password);
    await expect(page).toHaveURL(/\/dashboard/);

    // Act
    await page.goto('/admin');

    // Assert — SIT emphasises interface/contract-level behaviour: a
    // standard-role user must receive an access-denied response, not a
    // silently degraded page.
    await expect(page.getByRole('heading', { name: 'Access denied' })).toBeVisible();
    await expect(page).not.toHaveURL(/\/admin\/dashboard/);

    // Cleanup — no state was created by a denied navigation attempt.
  });
});
