import asyncio
import json
import time

import anyio

from app.agents.automation import automation_agent
from app.agents.automation.automation_agent import AutomationScriptAgent

VALID_CONTRACT_JSON = json.dumps({
    "contractVersion": "1.0",
    "testCaseId": "TC-0001",
    "requirementId": "REQ-0001",
    "scriptType": "playwright-typescript",
    "environmentProfile": "QA",
    "businessFlow": "Valid login succeeds",
    "pageObjects": [{
        "name": "LoginPage",
        "elements": [{"name": "usernameInput", "locatorStrategy": "label", "locatorValue": "Username"}],
    }],
    "steps": [{"phase": "act", "action": "fill", "target": "LoginPage.usernameInput", "value": "someone"}],
    "assertions": [{"type": "url", "target": "page", "expected": "dashboard"}],
})


class _FakeLLM:
    def __init__(self, response: str):
        self.response = response
        self.calls = 0

    async def achat(self, **_kwargs):
        self.calls += 1
        return self.response


def test_agent_compiles_a_valid_contract_into_a_runnable_script(monkeypatch):
    monkeypatch.setattr(automation_agent, "get_llm", lambda *_a, **_k: _FakeLLM(VALID_CONTRACT_JSON))

    async def run():
        return await AutomationScriptAgent().run(
            test_cases=[{"test_case_id": "TC-0001", "title": "Valid login"}],
            framework="playwright",
        )

    result = anyio.run(run)

    assert result.success is True
    scripts = result.data["scripts"]
    assert len(scripts) == 1
    script = scripts[0]
    assert script["test_case_id"] == "TC-0001"
    assert "GENERATED BY nxtQA Script Compiler" in script["code"]
    assert script["contract"]["testCaseId"] == "TC-0001"
    assert "pages/LoginPage.ts" in script["compiled_files"]
    assert script["execution_command"].startswith("npx playwright test")


def test_agent_reports_validation_error_without_crashing(monkeypatch):
    invalid_json = json.dumps({"contractVersion": "1.0", "steps": [{"phase": "act", "action": "not_a_real_action"}]})
    monkeypatch.setattr(automation_agent, "get_llm", lambda *_a, **_k: _FakeLLM(invalid_json))

    async def run():
        return await AutomationScriptAgent().run(
            test_cases=[{"test_case_id": "TC-0002", "title": "Broken"}],
            framework="playwright",
        )

    result = anyio.run(run)

    # Every test case in the wave failed, so the run failed — and it has to
    # carry the reason, or the caller can only report its own fallback.
    assert result.success is False
    assert result.data["scripts"] == []
    assert "Contract validation failed" in result.error
    assert any("Contract validation failed" in log["message"] for log in result.logs)


def test_agent_handles_malformed_json_gracefully(monkeypatch):
    monkeypatch.setattr(automation_agent, "get_llm", lambda *_a, **_k: _FakeLLM("not json at all"))

    async def run():
        return await AutomationScriptAgent().run(
            test_cases=[{"test_case_id": "TC-0003", "title": "Broken JSON"}],
            framework="playwright",
        )

    result = anyio.run(run)

    assert result.data["scripts"] == []
    assert any("parse error" in log["message"].lower() for log in result.logs)


def test_agent_pytest_framework_produces_pytest_script(monkeypatch):
    pytest_contract = json.dumps({
        "contractVersion": "1.0",
        "testCaseId": "TC-0004",
        "scriptType": "pytest-python",
        "environmentProfile": "SIT",
        "businessFlow": "API order check",
        "apiValidations": [{"method": "GET", "path": "/api/orders/latest", "expectedFields": {"status": "created"}}],
    })
    monkeypatch.setattr(automation_agent, "get_llm", lambda *_a, **_k: _FakeLLM(pytest_contract))

    async def run():
        return await AutomationScriptAgent().run(
            test_cases=[{"test_case_id": "TC-0004", "title": "API order check"}],
            framework="pytest",
        )

    result = anyio.run(run)

    assert result.success is True
    script = result.data["scripts"][0]
    assert script["file_path"].endswith(".py")
    assert script["execution_command"].startswith("pytest ")


# ── Concurrent wave generation (Playwright AI Studio) ────────────────────────
# A Studio wave submits up to 25 test cases in ONE agent call. Sequential
# generation blew through the agent's timeout on a live 9-test-case wave
# (240s ceiling, ~27s/TC average) — losing every already-compiled script in
# the wave, not just the slow ones. _generate_contracts now fans out with
# bounded concurrency (GENERATION_CONCURRENCY); these tests lock in that it
# actually runs concurrently (not serially disguised as async), respects the
# concurrency cap, and every test case still gets its own contract.

def _contract_json(test_case_id: str) -> str:
    return json.dumps({
        "contractVersion": "1.0", "testCaseId": test_case_id, "scriptType": "playwright-typescript",
        "environmentProfile": "QA", "businessFlow": f"Flow for {test_case_id}",
        "pageObjects": [{
            "name": "Page", "elements": [{"name": "el", "locatorStrategy": "label", "locatorValue": "El"}],
        }],
        "steps": [{"phase": "act", "action": "click", "target": "Page.el"}],
        "assertions": [{"type": "url", "target": "page", "expected": "ok"}],
    })


class _SlowKeyedLLM:
    """Returns a contract keyed to the test case id embedded in the prompt,
    after an artificial delay — lets tests assert real overlap in flight."""

    def __init__(self, delay: float = 0.05):
        self.delay = delay
        self.in_flight = 0
        self.max_in_flight = 0
        self.calls = 0

    async def achat(self, *, messages):
        self.calls += 1
        self.in_flight += 1
        self.max_in_flight = max(self.max_in_flight, self.in_flight)
        try:
            await asyncio.sleep(self.delay)
            prompt = messages[-1]["content"]
            for tc_id in ("TC-0001", "TC-0002", "TC-0003", "TC-0004", "TC-0005", "TC-0006"):
                if tc_id in prompt:
                    return _contract_json(tc_id)
            return _contract_json("TC-UNKNOWN")
        finally:
            self.in_flight -= 1


def test_wave_generation_runs_concurrently_not_serially(monkeypatch):
    llm = _SlowKeyedLLM(delay=0.1)
    monkeypatch.setattr(automation_agent, "get_llm", lambda *_a, **_k: llm)
    # Pinned rather than inherited: the real width is provider-aware now, and a
    # machine configured against a local single-model server resolves it to 1,
    # which would make this timing assertion fail for the right reason.
    monkeypatch.setattr(automation_agent, "_generation_concurrency", lambda: 5)

    test_cases = [{"test_case_id": f"TC-000{i}", "title": f"Case {i}"} for i in range(1, 6)]

    async def run():
        return await AutomationScriptAgent().run(test_cases=test_cases, framework="playwright")

    start = time.monotonic()
    result = anyio.run(run)
    elapsed = time.monotonic() - start

    assert result.success is True
    assert len(result.data["scripts"]) == 5
    assert {s["contract"]["testCaseId"] for s in result.data["scripts"]} == {
        "TC-0001", "TC-0002", "TC-0003", "TC-0004", "TC-0005",
    }
    # 5 sequential 0.1s calls would take >=0.5s; concurrent (cap=5) should
    # finish in roughly one delay's worth of wall-clock time.
    assert elapsed < 0.3
    assert llm.max_in_flight > 1


def test_wave_generation_respects_concurrency_cap(monkeypatch):
    llm = _SlowKeyedLLM(delay=0.05)
    monkeypatch.setattr(automation_agent, "get_llm", lambda *_a, **_k: llm)
    monkeypatch.setattr(automation_agent, "_generation_concurrency", lambda: 2)

    test_cases = [{"test_case_id": f"TC-000{i}", "title": f"Case {i}"} for i in range(1, 7)]

    async def run():
        return await AutomationScriptAgent().run(test_cases=test_cases, framework="playwright")

    result = anyio.run(run)

    assert len(result.data["scripts"]) == 6
    assert llm.max_in_flight == 2  # never more than the configured cap


def test_wave_generation_all_test_cases_present_even_with_one_slow_call(monkeypatch):
    """A wave must not lose the scripts that finished quickly just because
    one test case in the same wave needed a slow/retried call."""
    class _MixedSpeedLLM:
        def __init__(self):
            self.calls = 0

        async def achat(self, *, messages):
            self.calls += 1
            prompt = messages[-1]["content"]
            if "TC-SLOW" in prompt:
                await asyncio.sleep(0.15)
                return _contract_json("TC-SLOW")
            return _contract_json("TC-FAST")

    llm = _MixedSpeedLLM()
    monkeypatch.setattr(automation_agent, "get_llm", lambda *_a, **_k: llm)

    test_cases = [
        {"test_case_id": "TC-SLOW", "title": "Slow"},
        {"test_case_id": "TC-FAST", "title": "Fast"},
    ]

    async def run():
        return await AutomationScriptAgent().run(test_cases=test_cases, framework="playwright")

    result = anyio.run(run)

    assert {s["contract"]["testCaseId"] for s in result.data["scripts"]} == {"TC-SLOW", "TC-FAST"}


def test_wave_generation_stops_admitting_new_work_after_rate_limit(monkeypatch):
    """A 429 must stop tasks still queued behind the semaphore from ever
    calling the LLM — in-flight calls admitted before the limit hit are left
    to finish rather than aborted mid-call."""
    monkeypatch.setattr(automation_agent, "_generation_concurrency", lambda: 1)

    class _RateLimitedAfterFirstLLM:
        def __init__(self):
            self.calls = 0

        async def achat(self, *, messages):
            self.calls += 1
            if self.calls == 1:
                raise Exception("429 Too Many Requests: rate_limit_exceeded")
            return _contract_json("TC-SHOULD-NOT-RUN")

    llm = _RateLimitedAfterFirstLLM()
    monkeypatch.setattr(automation_agent, "get_llm", lambda *_a, **_k: llm)

    test_cases = [{"test_case_id": f"TC-000{i}", "title": f"Case {i}"} for i in range(1, 4)]

    async def run():
        return await AutomationScriptAgent().run(test_cases=test_cases, framework="playwright")

    result = anyio.run(run)

    # With concurrency=1, tasks run strictly one at a time behind the
    # semaphore — the first hits the rate limit and every subsequent queued
    # task must bail out before calling the LLM again.
    assert llm.calls == 1
    assert result.data["scripts"] == []
    assert any("rate limit" in log["message"].lower() for log in result.logs)


# ── a wave that failed must say why ───────────────────────────────────────────
# Observed live 2026-08-03: three test cases each failed with a specific,
# actionable provider error and the Studio could only report its own fallback,
# "Script generation produced no scripts", because the agent returned success.

def test_a_wave_where_every_test_case_failed_reports_the_reason(monkeypatch):
    class _ExplodingLLM:
        async def achat(self, **_kwargs):
            raise RuntimeError("Error code: 400 - Context size has been exceeded.")

    monkeypatch.setattr(automation_agent, "get_llm", lambda *_a, **_k: _ExplodingLLM())
    test_cases = [{"test_case_id": f"TC-000{i}", "title": f"Case {i}"} for i in range(1, 4)]

    async def run():
        return await AutomationScriptAgent().run(test_cases=test_cases, framework="playwright")

    result = anyio.run(run)

    assert result.success is False
    assert result.data["scripts"] == []
    # The cause is stated in full, and the count says how much else failed.
    assert "Context size has been exceeded" in result.error
    assert result.error.count("Context size has been exceeded") == 1
    assert "and 2 more test case(s) failed" in result.error


def test_a_partial_wave_still_succeeds_and_keeps_its_scripts(monkeypatch):
    """Scripts that compiled are real output; a sibling's failure must not
    discard them."""
    class _OneBadOneGoodLLM:
        def __init__(self):
            self.calls = 0

        async def achat(self, **_kwargs):
            self.calls += 1
            if self.calls == 1:
                raise RuntimeError("provider exploded")
            return VALID_CONTRACT_JSON

    monkeypatch.setattr(automation_agent, "get_llm", lambda *_a, **_k: _OneBadOneGoodLLM())
    monkeypatch.setattr(automation_agent, "_generation_concurrency", lambda: 1)
    test_cases = [
        {"test_case_id": "TC-0001", "title": "Fails"},
        {"test_case_id": "TC-0002", "title": "Works"},
    ]

    async def run():
        return await AutomationScriptAgent().run(test_cases=test_cases, framework="playwright")

    result = anyio.run(run)

    assert result.success is True
    assert len(result.data["scripts"]) == 1


def test_generation_concurrency_is_one_against_a_local_single_model_server(monkeypatch):
    """The whole reason the width became provider-aware: a local server shares
    one KV-cache budget across concurrent requests, so fanning out makes the
    entire wave fail together instead of going faster."""
    from app.config import Settings

    local = Settings(
        ai_gateway_enabled=True, ai_gateway_base_url="http://host.docker.internal:1234/v1",
        automation_generation_concurrency=0,
    )
    assert local.llm_provider_is_local_single_model is True
    assert local.resolved_automation_generation_concurrency == 1

    hosted = Settings(
        ai_gateway_enabled=False, default_llm_provider="groq",
        automation_generation_concurrency=0,
    )
    assert hosted.llm_provider_is_local_single_model is False
    assert hosted.resolved_automation_generation_concurrency == 5

    # An explicit setting always wins, local or not.
    pinned = Settings(
        ai_gateway_enabled=True, ai_gateway_base_url="http://host.docker.internal:1234/v1",
        automation_generation_concurrency=3,
    )
    assert pinned.resolved_automation_generation_concurrency == 3
