import json

import anyio

from app.agents.automation import automation_agent
from app.agents.automation.automation_agent import AutomationScriptAgent

VALID_CONTRACT_JSON = json.dumps({
    "contractVersion": "1.0",
    "testCaseId": "TC-0001",
    "requirementId": "REQ-0001",
    "scriptType": "playwright-typescript",
    "environmentProfile": "QA",
    "businessFlow": "Valid login succeeds",
    "pageObjects": [{
        "name": "LoginPage",
        "elements": [{"name": "usernameInput", "locatorStrategy": "label", "locatorValue": "Username"}],
    }],
    "steps": [{"phase": "act", "action": "fill", "target": "LoginPage.usernameInput", "value": "someone"}],
    "assertions": [{"type": "url", "target": "page", "expected": "dashboard"}],
})


class _FakeLLM:
    def __init__(self, response: str):
        self.response = response
        self.calls = 0

    async def achat(self, **_kwargs):
        self.calls += 1
        return self.response


def test_agent_compiles_a_valid_contract_into_a_runnable_script(monkeypatch):
    monkeypatch.setattr(automation_agent, "get_llm", lambda *_a, **_k: _FakeLLM(VALID_CONTRACT_JSON))

    async def run():
        return await AutomationScriptAgent().run(
            test_cases=[{"test_case_id": "TC-0001", "title": "Valid login"}],
            framework="playwright",
        )

    result = anyio.run(run)

    assert result.success is True
    scripts = result.data["scripts"]
    assert len(scripts) == 1
    script = scripts[0]
    assert script["test_case_id"] == "TC-0001"
    assert "GENERATED BY nxtQA Script Compiler" in script["code"]
    assert script["contract"]["testCaseId"] == "TC-0001"
    assert "pages/LoginPage.ts" in script["compiled_files"]
    assert script["execution_command"].startswith("npx playwright test")


def test_agent_reports_validation_error_without_crashing(monkeypatch):
    invalid_json = json.dumps({"contractVersion": "1.0", "steps": [{"phase": "act", "action": "not_a_real_action"}]})
    monkeypatch.setattr(automation_agent, "get_llm", lambda *_a, **_k: _FakeLLM(invalid_json))

    async def run():
        return await AutomationScriptAgent().run(
            test_cases=[{"test_case_id": "TC-0002", "title": "Broken"}],
            framework="playwright",
        )

    result = anyio.run(run)

    assert result.success is True  # agent-level success; the individual TC failed
    assert result.data["scripts"] == []
    assert any("Contract validation failed" in log["message"] for log in result.logs)


def test_agent_handles_malformed_json_gracefully(monkeypatch):
    monkeypatch.setattr(automation_agent, "get_llm", lambda *_a, **_k: _FakeLLM("not json at all"))

    async def run():
        return await AutomationScriptAgent().run(
            test_cases=[{"test_case_id": "TC-0003", "title": "Broken JSON"}],
            framework="playwright",
        )

    result = anyio.run(run)

    assert result.data["scripts"] == []
    assert any("parse error" in log["message"].lower() for log in result.logs)


def test_agent_pytest_framework_produces_pytest_script(monkeypatch):
    pytest_contract = json.dumps({
        "contractVersion": "1.0",
        "testCaseId": "TC-0004",
        "scriptType": "pytest-python",
        "environmentProfile": "SIT",
        "businessFlow": "API order check",
        "apiValidations": [{"method": "GET", "path": "/api/orders/latest", "expectedFields": {"status": "created"}}],
    })
    monkeypatch.setattr(automation_agent, "get_llm", lambda *_a, **_k: _FakeLLM(pytest_contract))

    async def run():
        return await AutomationScriptAgent().run(
            test_cases=[{"test_case_id": "TC-0004", "title": "API order check"}],
            framework="pytest",
        )

    result = anyio.run(run)

    assert result.success is True
    script = result.data["scripts"][0]
    assert script["file_path"].endswith(".py")
    assert script["execution_command"].startswith("pytest ")
