import pytest

from app.agents.automation.generation_contract import AutomationGenerationContract
from app.services.script_compiler import compile_contract
from app.services.script_compiler.compiler import UnsupportedContractVersionError

LOGIN_CONTRACT = {
    "contractVersion": "1.0",
    "testCaseId": "TC-0001",
    "requirementId": "REQ-0001",
    "scriptType": "playwright-typescript",
    "environmentProfile": "QA",
    "businessFlow": "Valid login succeeds",
    "testDataBindings": [{"name": "username", "placeholder": "${username}", "fallback": "demo"}],
    "pageObjects": [{
        "name": "LoginPage",
        "route": "/login",
        "elements": [
            {"name": "usernameInput", "locatorStrategy": "label", "locatorValue": "Username"},
            {"name": "submitButton", "locatorStrategy": "role", "locatorValue": "Sign in", "roleHint": "button"},
        ],
    }],
    "steps": [
        {"phase": "arrange", "action": "navigate", "value": "/login"},
        {"phase": "act", "action": "fill", "target": "LoginPage.usernameInput", "dataBinding": "username"},
        {"phase": "act", "action": "click", "target": "LoginPage.submitButton"},
    ],
    "assertions": [{"type": "url", "target": "page", "expected": "dashboard"}],
    "evidenceRequired": ["logged-in-user"],
    "cleanupActions": [{"type": "ui_action", "description": "session ends with browser context"}],
}


def _contract(**overrides) -> AutomationGenerationContract:
    data = dict(LOGIN_CONTRACT)
    data.update(overrides)
    return AutomationGenerationContract.model_validate(data)


def test_compile_playwright_produces_expected_file_tree():
    bundle = compile_contract(_contract())
    assert bundle.entry_path.startswith("specs/")
    assert bundle.entry_path.endswith(".spec.ts")
    assert "pages/LoginPage.ts" in bundle.files
    assert "fixtures/testData.fixture.ts" in bundle.files
    assert "utils/evidenceHelper.ts" in bundle.files
    # No API/DB validations declared -> those utils are not pulled in.
    assert "utils/apiClient.ts" not in bundle.files
    assert "utils/dbValidator.ts" not in bundle.files


def test_compile_playwright_spec_has_generation_header_and_structure():
    bundle = compile_contract(_contract())
    spec = bundle.files[bundle.entry_path]
    assert "GENERATED BY nxtQA Script Compiler" in spec
    assert "Test Case: TC-0001" in spec
    assert "Requirement: REQ-0001" in spec
    assert "// Arrange" in spec
    assert "// Act" in spec
    assert "// Assert" in spec
    assert "// Evidence" in spec
    assert "// Cleanup" in spec
    assert "loginPage.usernameInput.fill(TEST_DATA.username)" in spec
    assert "await expect(page).toHaveURL(new RegExp('dashboard'));" in spec


def test_url_assertion_with_slashes_does_not_break_regex_syntax():
    # A live run failed with invalid JS: `/https://mail.google.com//` — the
    # "//" from the URL's own scheme prematurely closed the bare regex
    # literal delimiter. new RegExp('...') has no delimiter to collide with.
    contract = _contract(assertions=[
        {"type": "url", "target": "page", "expected": "https://mail.google.com/"},
    ])
    bundle = compile_contract(contract)
    spec = bundle.files[bundle.entry_path]
    assert "await expect(page).toHaveURL(new RegExp('https://mail.google.com/'));" in spec
    assert "toHaveURL(/https://mail.google.com//)" not in spec


def test_wait_for_url_step_with_slashes_does_not_break_regex_syntax():
    contract = _contract(steps=[
        {"phase": "arrange", "action": "navigate", "value": "/login"},
        {"phase": "assert", "action": "wait_for_url", "value": "https://mail.google.com/"},
    ])
    bundle = compile_contract(contract)
    spec = bundle.files[bundle.entry_path]
    assert "await page.waitForURL(new RegExp('https://mail.google.com/'));" in spec


def test_compile_is_deterministic_for_identical_contracts():
    bundle_a = compile_contract(_contract())
    bundle_b = compile_contract(_contract())
    assert bundle_a.files == bundle_b.files
    assert bundle_a.entry_path == bundle_b.entry_path


def test_two_different_test_cases_produce_structurally_identical_skeletons():
    """Phase 2 exit criteria: same shape (imports/sections), only steps/page objects differ."""
    other = _contract(testCaseId="TC-0002", businessFlow="Different flow entirely")
    bundle_a = compile_contract(_contract())
    bundle_b = compile_contract(other)
    spec_a_lines = bundle_a.files[bundle_a.entry_path].splitlines()
    spec_b_lines = bundle_b.files[bundle_b.entry_path].splitlines()
    section_markers_a = [l.strip() for l in spec_a_lines if l.strip().startswith("//")]
    section_markers_b = [l.strip() for l in spec_b_lines if l.strip().startswith("//")]
    assert section_markers_a == section_markers_b


def test_custom_step_renders_as_todo_comment_not_fabricated_code():
    bundle = compile_contract(_contract(steps=[
        {"phase": "act", "action": "custom", "description": "do something the vocabulary can't express"}
    ]))
    spec = bundle.files[bundle.entry_path]
    assert "// TODO: do something the vocabulary can't express" in spec


def test_api_and_db_validations_pull_in_their_utils():
    bundle = compile_contract(_contract(
        apiValidations=[{"method": "GET", "path": "/api/orders/latest", "expectedFields": {"status": "created"}}],
        dbValidations=[{"table": "billing_ledger", "query": {"order_id": "latest"}}],
    ))
    assert "utils/apiClient.ts" in bundle.files
    assert "utils/dbValidator.ts" in bundle.files
    spec = bundle.files[bundle.entry_path]
    assert "getJson('/api/orders/latest', BASE_URL)" in spec
    assert "assertRowExists(DB_VALIDATION_ENDPOINT" in spec


def test_compile_pytest_produces_flat_file_bundle():
    bundle = compile_contract(_contract(
        scriptType="pytest-python",
        dbValidations=[{"table": "billing_ledger", "query": {"order_id": "latest"}}],
    ))
    assert bundle.entry_path.startswith("test_")
    assert bundle.entry_path.endswith(".py")
    assert "db_validator.py" in bundle.files
    assert "GENERATED BY nxtQA Script Compiler" in bundle.files[bundle.entry_path]


def test_unsupported_contract_version_raises():
    contract = _contract()
    # contract_version is validated by the Literal type at parse time, so
    # simulate an old/unsupported version by monkeypatching the compiler's
    # supported set instead of trying to construct an invalid contract.
    import app.services.script_compiler.compiler as compiler_module
    original = compiler_module.SUPPORTED_CONTRACT_VERSIONS
    compiler_module.SUPPORTED_CONTRACT_VERSIONS = frozenset()
    try:
        with pytest.raises(UnsupportedContractVersionError):
            compile_contract(contract)
    finally:
        compiler_module.SUPPORTED_CONTRACT_VERSIONS = original
