import pytest

from app.agents.automation.generation_contract import AutomationGenerationContract
from app.services.script_compiler import compile_contract
from app.services.script_compiler.compiler import UnsupportedContractVersionError
from app.services.script_compiler.naming import js_string_literal
from app.services.script_compiler.playwright_renderer import _escape_regex_literal

LOGIN_CONTRACT = {
    "contractVersion": "1.0",
    "testCaseId": "TC-0001",
    "requirementId": "REQ-0001",
    "scriptType": "playwright-typescript",
    "environmentProfile": "QA",
    "businessFlow": "Valid login succeeds",
    "testDataBindings": [{"name": "username", "placeholder": "${username}", "fallback": "demo"}],
    "pageObjects": [{
        "name": "LoginPage",
        "route": "/login",
        "elements": [
            {"name": "usernameInput", "locatorStrategy": "label", "locatorValue": "Username"},
            {"name": "submitButton", "locatorStrategy": "role", "locatorValue": "Sign in", "roleHint": "button"},
        ],
    }],
    "steps": [
        {"phase": "arrange", "action": "navigate", "value": "/login"},
        {"phase": "act", "action": "fill", "target": "LoginPage.usernameInput", "dataBinding": "username"},
        {"phase": "act", "action": "click", "target": "LoginPage.submitButton"},
    ],
    "assertions": [{"type": "url", "target": "page", "expected": "dashboard"}],
    "evidenceRequired": ["logged-in-user"],
    "cleanupActions": [{"type": "ui_action", "description": "session ends with browser context"}],
}


def _contract(**overrides) -> AutomationGenerationContract:
    data = dict(LOGIN_CONTRACT)
    data.update(overrides)
    return AutomationGenerationContract.model_validate(data)


def test_compile_playwright_produces_expected_file_tree():
    bundle = compile_contract(_contract())
    assert bundle.entry_path.startswith("specs/")
    assert bundle.entry_path.endswith(".spec.ts")
    assert "pages/LoginPage.ts" in bundle.files
    assert "fixtures/testData.fixture.ts" in bundle.files
    assert "utils/evidenceHelper.ts" in bundle.files
    # No API/DB validations declared -> those utils are not pulled in.
    assert "utils/apiClient.ts" not in bundle.files
    assert "utils/dbValidator.ts" not in bundle.files


def test_compile_playwright_spec_has_generation_header_and_structure():
    bundle = compile_contract(_contract())
    spec = bundle.files[bundle.entry_path]
    assert "GENERATED BY nxtQA Script Compiler" in spec
    assert "Test Case: TC-0001" in spec
    assert "Requirement: REQ-0001" in spec
    assert "// Arrange" in spec
    assert "// Act" in spec
    assert "// Assert" in spec
    assert "// Evidence" in spec
    assert "// Cleanup" in spec
    assert "loginPage.usernameInput.fill(TEST_DATA.username)" in spec
    assert "await expect(page).toHaveURL(new RegExp('dashboard'));" in spec


def test_compile_renders_nth_suffix_for_disambiguated_elements():
    """A live run's strict-mode-violation bug: two "Show password" buttons
    with the same accessible name compiled to the same non-unique locator.
    An element carrying `nth` must render with a trailing .nth(N)."""
    contract = _contract(pageObjects=[{
        "name": "SignUpPage",
        "elements": [
            {"name": "showPasswordToggle", "locatorStrategy": "role",
             "locatorValue": "Show password", "roleHint": "button", "nth": 1},
        ],
    }], steps=[
        {"phase": "act", "action": "click", "target": "SignUpPage.showPasswordToggle"},
    ])
    bundle = compile_contract(contract)
    page_object_file = bundle.files["pages/SignUpPage.ts"]
    assert (
        "this.showPasswordToggle = page.getByRole('button', "
        "{ name: 'Show password', exact: true }).nth(1);"
    ) in page_object_file


def test_url_assertion_with_slashes_does_not_break_regex_syntax():
    # A live run failed with invalid JS: `/https://mail.google.com//` — the
    # "//" from the URL's own scheme prematurely closed the bare regex
    # literal delimiter. new RegExp('...') has no delimiter to collide with.
    # The domain's dots are now regex-escaped too (see the escaping test
    # below) — this test only asserts the delimiter-collision fix.
    contract = _contract(assertions=[
        {"type": "url", "target": "page", "expected": "https://mail.google.com/"},
    ])
    bundle = compile_contract(contract)
    spec = bundle.files[bundle.entry_path]
    expected = js_string_literal(_escape_regex_literal("https://mail.google.com/"))
    assert f"await expect(page).toHaveURL(new RegExp({expected}));" in spec
    assert "toHaveURL(/https://mail.google.com//)" not in spec


def test_wait_for_url_step_with_slashes_does_not_break_regex_syntax():
    contract = _contract(steps=[
        {"phase": "arrange", "action": "navigate", "value": "/login"},
        {"phase": "assert", "action": "wait_for_url", "value": "https://mail.google.com/"},
    ])
    bundle = compile_contract(contract)
    spec = bundle.files[bundle.entry_path]
    expected = js_string_literal(_escape_regex_literal("https://mail.google.com/"))
    assert f"await page.waitForURL(new RegExp({expected}));" in spec


# ── Regex-metacharacter escaping (Playwright AI Studio) ──────────────────────
# A live run's compiled scripts correctly navigated to the exact target page
# (confirmed in the runner logs) yet still timed out on wait_for_url/url
# assertions — root cause: a captured URL fragment like
# "/sign-up?role=candidate" was passed straight into `new RegExp(...)`
# unescaped, so the '?' was interpreted as "the preceding character is
# optional" instead of a literal question mark. Query strings are the norm
# for real captured URLs, so this silently broke nearly every multi-role /
# parameterized route.

def test_escape_regex_literal_escapes_query_string_question_mark():
    assert _escape_regex_literal("/sign-up?role=candidate") == "/sign-up\\?role=candidate"


def test_escape_regex_literal_escapes_dots():
    assert _escape_regex_literal("mail.google.com") == "mail\\.google\\.com"


def test_escape_regex_literal_leaves_plain_paths_unchanged():
    assert _escape_regex_literal("/dashboard") == "/dashboard"
    assert _escape_regex_literal("dashboard") == "dashboard"


def test_escape_regex_literal_does_not_escape_forward_slashes():
    # new RegExp('...') is the string constructor form (no /pattern/
    # delimiters), so '/' is just a literal character here — only the
    # actual JS/TS regex metacharacter set needs escaping.
    assert _escape_regex_literal("https://mail.google.com/") == "https://mail\\.google\\.com/"


def test_wait_for_url_with_real_query_string_matches_the_page_it_navigated_to():
    """End-to-end reproduction of the live bug: a wait_for_url value that is
    an exact real captured URL fragment must compile to a regex whose
    escaped source, once JS-parses the string literal, matches that exact
    fragment — verified here by decoding the compiler's own escaping the
    same way a JS engine would (backslash-doubling reversed), rather than
    trusting the raw source text."""
    real_target = "/sign-up?role=candidate"
    contract = _contract(steps=[
        {"phase": "arrange", "action": "navigate", "value": "/"},
        {"phase": "act", "action": "wait_for_url", "value": real_target},
    ])
    bundle = compile_contract(contract)
    spec = bundle.files[bundle.entry_path]

    import re as _re
    match = _re.search(r"new RegExp\('((?:[^'\\]|\\.)*)'\)", spec)
    assert match, f"no new RegExp(...) call found in:\n{spec}"
    js_string_content = match.group(1)
    # Reverse JS string-literal escaping (\\ -> \) to get the actual regex
    # source the JS engine would compile, then confirm it matches the real
    # URL as a substring — exactly what waitForURL needs to succeed.
    regex_source = js_string_content.replace("\\\\", "\\")
    assert _re.search(regex_source, real_target), (
        f"compiled regex source {regex_source!r} does not match the real target {real_target!r}"
    )


def test_compile_is_deterministic_for_identical_contracts():
    bundle_a = compile_contract(_contract())
    bundle_b = compile_contract(_contract())
    assert bundle_a.files == bundle_b.files
    assert bundle_a.entry_path == bundle_b.entry_path


def test_two_different_test_cases_produce_structurally_identical_skeletons():
    """Phase 2 exit criteria: same shape (imports/sections), only steps/page objects differ."""
    other = _contract(testCaseId="TC-0002", businessFlow="Different flow entirely")
    bundle_a = compile_contract(_contract())
    bundle_b = compile_contract(other)
    spec_a_lines = bundle_a.files[bundle_a.entry_path].splitlines()
    spec_b_lines = bundle_b.files[bundle_b.entry_path].splitlines()
    section_markers_a = [l.strip() for l in spec_a_lines if l.strip().startswith("//")]
    section_markers_b = [l.strip() for l in spec_b_lines if l.strip().startswith("//")]
    assert section_markers_a == section_markers_b


def test_custom_step_renders_as_todo_comment_not_fabricated_code():
    bundle = compile_contract(_contract(steps=[
        {"phase": "act", "action": "custom", "description": "do something the vocabulary can't express"}
    ]))
    spec = bundle.files[bundle.entry_path]
    assert "// TODO: do something the vocabulary can't express" in spec


def test_api_and_db_validations_pull_in_their_utils():
    bundle = compile_contract(_contract(
        apiValidations=[{"method": "GET", "path": "/api/orders/latest", "expectedFields": {"status": "created"}}],
        dbValidations=[{"table": "billing_ledger", "query": {"order_id": "latest"}}],
    ))
    assert "utils/apiClient.ts" in bundle.files
    assert "utils/dbValidator.ts" in bundle.files
    spec = bundle.files[bundle.entry_path]
    # The declared method and status are both rendered — expectedStatus used to
    # be dropped entirely, so a contract expecting 201 accepted any 2xx.
    assert "requestJson('/api/orders/latest', BASE_URL, { method: 'GET', expectedStatus: 200 })" in spec
    assert "expect(apiResult1.status).toBe(200);" in spec
    assert "expect(apiResult1.body.status).toBe('created');" in spec
    assert "assertRowExists(DB_VALIDATION_ENDPOINT" in spec


def test_api_validation_honours_non_default_status_and_method():
    bundle = compile_contract(_contract(
        apiValidations=[{"method": "POST", "path": "/api/orders", "expectedStatus": 201}],
    ))
    spec = bundle.files[bundle.entry_path]
    assert "method: 'POST', expectedStatus: 201" in spec
    assert "expect(apiResult1.status).toBe(201);" in spec


def test_api_validation_rejects_unsafe_expected_field_name():
    with pytest.raises(ValueError, match="not a valid property path"):
        compile_contract(_contract(
            apiValidations=[{
                "path": "/api/orders",
                "expectedFields": {"status'] ; process.exit(0); //": "created"},
            }],
        ))


def test_db_validation_expect_found_false_asserts_absence():
    """expect_found=false used to render assertRowExists plus a TODO comment —
    the exact opposite of the declared contract (AUT-005)."""
    bundle = compile_contract(_contract(
        dbValidations=[{
            "table": "billing_ledger",
            "query": {"order_id": "cancelled"},
            "expectFound": False,
        }],
    ))
    spec = bundle.files[bundle.entry_path]
    assert "assertRowAbsent(DB_VALIDATION_ENDPOINT" in spec
    assert "assertRowExists" not in spec
    assert "TODO" not in spec
    assert "import { assertRowAbsent } from '../utils/dbValidator';" in spec
    assert "assertRowAbsent" in bundle.files["utils/dbValidator.ts"]


def test_pytest_db_validation_expect_found_false_asserts_absence():
    bundle = compile_contract(_contract(
        scriptType="pytest-python",
        dbValidations=[{
            "table": "billing_ledger",
            "query": {"order_id": "cancelled"},
            "expectFound": False,
        }],
    ))
    module = bundle.files[bundle.entry_path]
    assert "assert_row_absent(DB_VALIDATION_ENDPOINT" in module
    assert "from db_validator import assert_row_absent" in module
    assert "TODO" not in module
    assert "def assert_row_absent" in bundle.files["db_validator.py"]


def test_declared_evidence_is_not_rendered_as_captured():
    """The contract carries evidence names with no value binding, so the old
    attachEvidence(name, name) attached the label as its own content and read
    as captured evidence (AUT-005)."""
    bundle = compile_contract(_contract(evidenceRequired=["order_id", "invoice_pdf"]))
    spec = bundle.files[bundle.entry_path]
    assert "declareRequiredEvidence(testInfo, 'order_id');" in spec
    assert "attachEvidence(testInfo, 'order_id', 'order_id')" not in spec
    assert "not_captured" in bundle.files["utils/evidenceHelper.ts"]


def test_pytest_declared_evidence_is_not_printed_as_captured():
    bundle = compile_contract(_contract(
        scriptType="pytest-python", evidenceRequired=["order_id"],
    ))
    module = bundle.files[bundle.entry_path]
    assert "evidence:order_id=not_captured" in module
    assert "=captured" not in module


def test_api_cleanup_action_ships_the_api_client_it_calls():
    """A contract whose only API usage is a cleanup action still renders
    getJson and BASE_URL, so both the helper file and the constant must exist."""
    bundle = compile_contract(_contract(
        cleanupActions=[{"type": "api_call", "description": "delete order", "target": "/api/orders/1"}],
    ))
    spec = bundle.files[bundle.entry_path]
    assert "utils/apiClient.ts" in bundle.files
    assert "import { getJson } from '../utils/apiClient';" in spec
    assert "const BASE_URL = process.env.BASE_URL ?? '';" in spec


def test_compile_pytest_produces_flat_file_bundle():
    bundle = compile_contract(_contract(
        scriptType="pytest-python",
        dbValidations=[{"table": "billing_ledger", "query": {"order_id": "latest"}}],
    ))
    assert bundle.entry_path.startswith("test_")
    assert bundle.entry_path.endswith(".py")
    assert "db_validator.py" in bundle.files
    assert "GENERATED BY nxtQA Script Compiler" in bundle.files[bundle.entry_path]


def test_pytest_wait_for_url_escapes_regex_metacharacters():
    """Same live bug, pytest renderer: re.compile() on an unescaped captured
    URL fragment misinterprets '?'/'.' etc. as regex syntax instead of
    literal characters."""
    real_target = "/sign-up?role=candidate"
    bundle = compile_contract(_contract(
        scriptType="pytest-python",
        steps=[
            {"phase": "arrange", "action": "navigate", "value": "/"},
            {"phase": "act", "action": "wait_for_url", "value": real_target},
        ],
    ))
    spec = bundle.files[bundle.entry_path]

    import re as _re
    match = _re.search(r're\.compile\("((?:[^"\\]|\\.)*)"\)', spec)
    assert match, f"no re.compile(...) call found in:\n{spec}"
    # py_string_literal uses the same backslash-doubling as js_string_literal
    # — reverse it to recover the actual regex source Python would compile.
    regex_source = match.group(1).replace("\\\\", "\\")
    assert _re.search(regex_source, real_target), (
        f"compiled regex source {regex_source!r} does not match the real target {real_target!r}"
    )


def test_unsupported_contract_version_raises():
    contract = _contract()
    # contract_version is validated by the Literal type at parse time, so
    # simulate an old/unsupported version by monkeypatching the compiler's
    # supported set instead of trying to construct an invalid contract.
    import app.services.script_compiler.compiler as compiler_module
    original = compiler_module.SUPPORTED_CONTRACT_VERSIONS
    compiler_module.SUPPORTED_CONTRACT_VERSIONS = frozenset()
    try:
        with pytest.raises(UnsupportedContractVersionError):
            compile_contract(contract)
    finally:
        compiler_module.SUPPORTED_CONTRACT_VERSIONS = original
