"""
Static Quality Gate (Phase 2.5).

Runs on every compiled script before a human ever reviews it. Combines:
  1. The existing `automation_intelligence` rule engine (hard waits, weak
     locators, missing assertions, hardcoded data/credentials) — its `severity`
     field decides block vs warn here (high => block, medium/low => warn).
  2. Two new ADR-001-specific checks: the compiler-stamped generation header
     must be present, and it must carry a Test Case / Requirement mapping —
     this is what makes "no free-form script generation" enforceable rather
     than aspirational.
  3. An optional syntax check (`npx playwright test --list`) when Node/
     Playwright are available on this host — skipped, not failed, otherwise.

A project may record accepted exceptions on a script
(`metadata_["static_gate_exceptions"]`, a list of finding `kind` strings,
e.g. `["hard_wait"]`) — an exempted kind never blocks, only warns.
"""
from __future__ import annotations

import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from types import SimpleNamespace

from app.models.automation_script import AutomationScript
from app.services import automation_intelligence

_GENERATION_HEADER_MARKER = "GENERATED BY nxtQA Script Compiler"
_TC_HEADER_RE = re.compile(r"Test Case:\s*\S+", re.IGNORECASE)
_REQ_HEADER_RE = re.compile(r"Requirement:\s*\S+", re.IGNORECASE)

# automation_intelligence.Recommendation.severity -> gate severity, unless
# the finding's `kind` is in the script's accepted-exceptions list.
_BLOCKING_SEVERITIES = {"high"}


@dataclass
class GateViolation:
    code: str
    message: str
    severity: str  # "block" | "warn"

    def as_dict(self) -> dict:
        return {"code": self.code, "message": self.message, "severity": self.severity}


@dataclass
class GateResult:
    passed: bool
    violations: list[GateViolation] = field(default_factory=list)
    warnings: list[GateViolation] = field(default_factory=list)
    syntax_check: str = "skipped"  # "passed" | "failed" | "skipped"
    syntax_check_detail: str | None = None

    def as_dict(self) -> dict:
        return {
            "passed": self.passed,
            "violations": [v.as_dict() for v in self.violations],
            "warnings": [w.as_dict() for w in self.warnings],
            "syntax_check": self.syntax_check,
            "syntax_check_detail": self.syntax_check_detail,
        }


def _accepted_exceptions(script: AutomationScript) -> set[str]:
    return set((script.metadata_ or {}).get("static_gate_exceptions", []))


def _check_generation_header(code: str) -> GateViolation | None:
    if _GENERATION_HEADER_MARKER not in code:
        return GateViolation(
            code="missing_generation_header",
            message=(
                "Script has no nxtQA Script Compiler generation header. Per ADR-001, no "
                "script may be persisted unless it was rendered by the Script Compiler."
            ),
            severity="block",
        )
    return None


def _check_tc_req_mapping(code: str) -> GateViolation | None:
    if not (_TC_HEADER_RE.search(code) and _REQ_HEADER_RE.search(code)):
        return GateViolation(
            code="missing_tc_req_mapping",
            message="Script header is missing a Test Case / Requirement mapping.",
            severity="block",
        )
    return None


def _analysis_target(script: AutomationScript):
    """The rule engine must see the WHOLE bundle, not just the entry spec —
    locators typically live in page-object files, not the spec itself. Falls
    back to `script` unchanged for legacy single-file scripts."""
    if not script.compiled_files:
        return script
    combined = "\n\n".join(script.compiled_files.values())
    return SimpleNamespace(id=script.id, framework=script.framework, code=combined)


def _rule_engine_violations(script: AutomationScript, exceptions: set[str]) -> tuple[list[GateViolation], list[GateViolation]]:
    violations: list[GateViolation] = []
    warnings: list[GateViolation] = []
    report = automation_intelligence.analyze_script(_analysis_target(script))

    for rec in report.recommendations:
        blocking = rec.severity in _BLOCKING_SEVERITIES and rec.kind not in exceptions
        gv = GateViolation(code=rec.kind, message=f"{rec.title}: {rec.description}", severity="block" if blocking else "warn")
        (violations if blocking else warnings).append(gv)

    for finding in report.locators:
        warnings.append(GateViolation(
            code="weak_locator",
            message=f"{finding.current} — {finding.rationale}",
            severity="warn",
        ))

    return violations, warnings


def _syntax_check(entry_path: str, workspace: Path) -> tuple[str, str | None]:
    """Best-effort `npx playwright test --list` against a materialized
    workspace. Returns ("skipped"|"passed"|"failed", detail)."""
    if shutil.which("npx") is None:
        return "skipped", "npx not available on this host"
    try:
        proc = subprocess.run(
            ["npx", "playwright", "test", entry_path, "--list"],
            cwd=str(workspace),
            capture_output=True,
            text=True,
            timeout=60,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        return "skipped", f"syntax check could not run: {exc}"
    if proc.returncode != 0:
        return "failed", (proc.stderr or proc.stdout)[:2000]
    return "passed", None


def run_static_quality_gate(
    script: AutomationScript,
    *,
    workspace: Path | None = None,
) -> GateResult:
    """Run the deterministic gate against `script.code`. Pass `workspace`
    (a materialized bundle directory with node_modules resolvable) to also
    attempt the optional syntax check; omit it to run only the code-level
    checks (e.g. immediately after compilation, before materialization)."""
    code = script.code or ""
    exceptions = _accepted_exceptions(script)
    violations: list[GateViolation] = []

    header_violation = _check_generation_header(code)
    if header_violation:
        violations.append(header_violation)
    mapping_violation = _check_tc_req_mapping(code)
    if mapping_violation:
        violations.append(mapping_violation)

    rule_violations, warnings = _rule_engine_violations(script, exceptions)
    violations.extend(rule_violations)

    syntax_status, syntax_detail = "skipped", None
    if workspace is not None and script.file_path:
        syntax_status, syntax_detail = _syntax_check(script.file_path, workspace)
        if syntax_status == "failed":
            violations.append(GateViolation(
                code="syntax_check_failed",
                message=syntax_detail or "playwright test --list failed",
                severity="block",
            ))

    return GateResult(
        passed=not violations,
        violations=violations,
        warnings=warnings,
        syntax_check=syntax_status,
        syntax_check_detail=syntax_detail,
    )
