// UI-021 Script Editor — Tab B.
//
// THIS IS NOT AN EDITABLE CODE EDITOR, and that is a governance guarantee
// rather than a missing feature. ADR-001 makes the Script Compiler the only
// writer of script source, and `static_quality_gate` enforces it: a hand-edited
// file loses the `GENERATED BY nxtQA Script Compiler` header and is hard-blocked
// by the platform's own gate. A save-capable editor here would put the screen in
// permanent conflict with that gate.
//
// So the only path to changing code is to change the behaviour and recompile.
// Every rendered line is traceable to a validated contract.

"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  AlertTriangle,
  ChevronDown,
  ChevronRight,
  FileCode2,
  Lock,
  Play,
  RefreshCw,
  ShieldCheck,
  XCircle,
} from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useToast } from "@/components/ui/toast";
import { cn } from "@/lib/utils";
import {
  automationScriptApi,
  type AutomationAsset,
  type CompiledScript,
  type DryRunOutcome,
  type DryRunTestResult,
  type RunnerFrameworkStatus,
} from "@/lib/api";

import { messageFromError, Panel } from "./suite-shared";

/** Build a directory tree from the bundle's flat "dir/file" keys. */
interface TreeNode {
  name: string;
  path: string;
  children: TreeNode[];
  isFile: boolean;
}

function buildTree(paths: string[]): TreeNode[] {
  const root: TreeNode[] = [];
  for (const full of paths.sort()) {
    const parts = full.split("/");
    let level = root;
    let prefix = "";
    parts.forEach((part, i) => {
      prefix = prefix ? `${prefix}/${part}` : part;
      const isFile = i === parts.length - 1;
      let node = level.find((n) => n.name === part && n.isFile === isFile);
      if (!node) {
        node = { name: part, path: prefix, children: [], isFile };
        level.push(node);
      }
      level = node.children;
    });
  }
  return root;
}

function TreeView({
  nodes,
  selected,
  onSelect,
  depth = 0,
}: {
  nodes: TreeNode[];
  selected: string | null;
  onSelect: (path: string) => void;
  depth?: number;
}) {
  const [collapsed, setCollapsed] = useState<Record<string, boolean>>({});
  return (
    <ul>
      {nodes.map((node) => (
        <li key={node.path}>
          {node.isFile ? (
            <button
              type="button"
              onClick={() => onSelect(node.path)}
              style={{ paddingLeft: `${depth * 10 + 8}px` }}
              className={cn(
                "flex w-full items-center gap-1 py-0.5 pr-2 text-left text-[11px]",
                selected === node.path
                  ? "bg-app-brand-75 font-medium text-app-brand-800"
                  : "text-gray-600 hover:bg-gray-50",
              )}
            >
              <FileCode2 className="h-3 w-3 shrink-0 text-gray-400" />
              <span className="truncate">{node.name}</span>
            </button>
          ) : (
            <>
              <button
                type="button"
                onClick={() => setCollapsed((c) => ({ ...c, [node.path]: !c[node.path] }))}
                style={{ paddingLeft: `${depth * 10 + 4}px` }}
                className="flex w-full items-center gap-0.5 py-0.5 text-left text-[11px] font-semibold text-gray-700 hover:bg-gray-50"
              >
                {collapsed[node.path] ? (
                  <ChevronRight className="h-3 w-3" />
                ) : (
                  <ChevronDown className="h-3 w-3" />
                )}
                {node.name}/
              </button>
              {!collapsed[node.path] ? (
                <TreeView
                  nodes={node.children}
                  selected={selected}
                  onSelect={onSelect}
                  depth={depth + 1}
                />
              ) : null}
            </>
          )}
        </li>
      ))}
    </ul>
  );
}

function StatusPill({ status }: { status: string }) {
  const tone =
    status === "pass"
      ? "bg-emerald-50 text-emerald-700"
      : status === "skip"
        ? "bg-gray-100 text-gray-600"
        : "bg-red-50 text-red-700";
  return (
    <span className={cn("rounded px-1.5 py-0.5 text-[10px] font-semibold", tone)}>{status}</span>
  );
}

export function ScriptEditorTab({
  memberId,
  asset,
  onReload,
  onBusyChange,
  onEditBehaviour,
}: {
  memberId: number;
  asset: AutomationAsset;
  onReload: () => Promise<void> | void;
  onBusyChange: (label: string | null) => void;
  onEditBehaviour: () => void;
}) {
  const { toast } = useToast();

  const [script, setScript] = useState<CompiledScript | null>(null);
  const [unavailable, setUnavailable] = useState<string | null>(null);
  const [history, setHistory] = useState<DryRunTestResult[]>([]);
  const [selectedPath, setSelectedPath] = useState<string | null>(null);
  const [runners, setRunners] = useState<RunnerFrameworkStatus[]>([]);
  const [outcome, setOutcome] = useState<DryRunOutcome | null>(null);
  const [compiling, setCompiling] = useState(false);
  const [running, setRunning] = useState(false);
  const [loading, setLoading] = useState(true);

  const loadScript = useCallback(async () => {
    setLoading(true);
    try {
      const res = await automationScriptApi.get(memberId);
      setScript(res.data.script);
      setUnavailable(res.data.unavailable);
      setHistory(res.data.dry_runs);
      setSelectedPath(res.data.script?.entry_path ?? null);
    } catch (err) {
      toast({ title: "Could not load the script", description: messageFromError(err), variant: "error" });
    } finally {
      setLoading(false);
    }
  }, [memberId, toast]);

  useEffect(() => {
    void loadScript();
  }, [loadScript]);

  useEffect(() => {
    void automationScriptApi
      .runnerStatus()
      .then((res) => setRunners(res.data.frameworks))
      .catch(() => setRunners([]));
  }, []);

  const files = useMemo(() => script?.compiled_files ?? {}, [script?.compiled_files]);
  const tree = useMemo(() => buildTree(Object.keys(files)), [files]);
  const source = selectedPath ? files[selectedPath] ?? "" : "";

  const runner = runners.find(
    (r) => r.framework === (script?.framework ?? asset.header.framework.value ?? "playwright"),
  );
  const runnerBlocked = runner ? !runner.available : false;

  const handleCompile = useCallback(async () => {
    setCompiling(true);
    onBusyChange("Compiling…");
    try {
      const res = await automationScriptApi.compile(memberId);
      toast({
        title: `Compiled ${res.data.script_id} v${res.data.version}`,
        description: `${res.data.file_count} files from the validated contract.`,
      });
      await loadScript();
      await onReload();
    } catch (err) {
      toast({ title: "Compile failed", description: messageFromError(err), variant: "error" });
    } finally {
      setCompiling(false);
      onBusyChange(null);
    }
  }, [loadScript, memberId, onBusyChange, onReload, toast]);

  const handleDryRun = useCallback(async () => {
    setRunning(true);
    onBusyChange("Running dry run…");
    try {
      const res = await automationScriptApi.dryRun(memberId);
      setOutcome(res.data);
      toast({
        title: res.data.all_passed ? "Dry run passed" : "Dry run finished with failures",
        description: `${res.data.results.length} test(s) · exit ${res.data.exit_code ?? "—"}`,
        variant: res.data.all_passed ? undefined : "error",
      });
      await loadScript();
      await onReload();
    } catch (err) {
      toast({ title: "Dry run could not start", description: messageFromError(err), variant: "error" });
    } finally {
      setRunning(false);
      onBusyChange(null);
    }
  }, [loadScript, memberId, onBusyChange, onReload, toast]);

  if (!script) {
    return (
      <div className="rounded-lg border border-dashed border-gray-300 bg-gray-50 p-6 text-center">
        <p className="text-[12px] font-semibold text-gray-700">Not compiled yet</p>
        <p className="mx-auto mt-1 max-w-lg text-[11px] text-gray-500">
          {unavailable ?? "This asset has not been compiled."}
        </p>
        <Button
          size="sm"
          className="mt-3 h-7 text-[11px]"
          disabled={compiling || loading || !asset.ir_validation?.valid}
          title={
            !asset.ir_validation?.valid
              ? "The behaviour must validate before it can be compiled."
              : undefined
          }
          onClick={() => void handleCompile()}
        >
          <RefreshCw className={cn("mr-1 h-3 w-3", compiling && "animate-spin")} />
          Compile from behaviour
        </Button>
      </div>
    );
  }

  const gate = script.static_gate_result;

  return (
    <div className="space-y-3">
      {/* Entry point. Framework is INHERITED and read-only — changing it is a
          suite-level action, where UI-018's conflict detection can respond. */}
      <div className="rounded-lg border border-gray-200 bg-white p-3">
        <div className="flex flex-wrap items-end justify-between gap-3">
          <div className="flex flex-wrap items-end gap-5">
            <div>
              <p className="text-[9px] font-semibold uppercase tracking-wide text-gray-400">
                Language / Framework
              </p>
              <p
                className="text-[12px] font-medium text-gray-800"
                title={asset.header.framework.source ?? undefined}
              >
                {script.framework}
                <span className="ml-1 text-[10px] font-normal text-gray-400">
                  (inherited — read-only)
                </span>
              </p>
            </div>
            <div>
              <p className="text-[9px] font-semibold uppercase tracking-wide text-gray-400">
                Entry file
              </p>
              <select
                className="h-6 rounded border border-gray-200 bg-white px-1 text-[11px]"
                value={selectedPath ?? ""}
                onChange={(e) => setSelectedPath(e.target.value)}
              >
                {Object.keys(files).map((p) => (
                  <option key={p} value={p}>
                    {p}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <p className="text-[9px] font-semibold uppercase tracking-wide text-gray-400">
                Compiler
              </p>
              <p className="text-[12px] text-gray-700">{script.compiler_version ?? "—"}</p>
            </div>
          </div>
          <Button
            variant="outline"
            size="sm"
            className="h-7 text-[11px]"
            disabled={compiling}
            onClick={() => void handleCompile()}
          >
            <RefreshCw className={cn("mr-1 h-3 w-3", compiling && "animate-spin")} />
            Regenerate
          </Button>
        </div>
      </div>

      {/* Code — read-only, with the file tree over the whole bundle. */}
      <div className="grid grid-cols-1 gap-0 overflow-hidden rounded-lg border border-gray-200 bg-white md:grid-cols-[220px_minmax(0,1fr)]">
        <div className="border-b border-gray-200 py-2 md:border-b-0 md:border-r">
          <p className="px-2 pb-1 text-[10px] font-extrabold uppercase tracking-wide text-gray-500">
            Compiled files ({Object.keys(files).length})
          </p>
          <TreeView nodes={tree} selected={selectedPath} onSelect={setSelectedPath} />
        </div>
        <div className="min-w-0">
          <div className="flex items-center justify-between border-b border-gray-100 px-3 py-1.5">
            <span className="truncate text-[11px] font-medium text-gray-700">
              {selectedPath ?? "—"}
            </span>
            <button
              type="button"
              onClick={onEditBehaviour}
              className="text-[10px] font-bold text-[#B71920] hover:underline"
            >
              Edit behaviour
            </button>
          </div>
          <pre className="max-h-[460px] overflow-auto bg-gray-50 p-3 text-[11px] leading-relaxed text-gray-800">
            {source || "Select a file."}
          </pre>
          <div className="flex items-center gap-1.5 border-t border-gray-100 px-3 py-1.5 text-[10px] text-gray-500">
            <Lock className="h-3 w-3" />
            Read-only: generated by the Script Compiler. Change the behaviour and recompile.
          </div>
        </div>
      </div>

      {/* Locator policy + static gate, both from the persisted verdict. */}
      <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
        <Panel title="Static quality gate">
          {!gate ? (
            <p className="text-[11px] text-gray-400">The gate has not run for this version.</p>
          ) : (
            <div className="space-y-1.5">
              <div className="flex items-center gap-2">
                {gate.passed ? (
                  <Badge variant="success" className="text-[9px]">
                    <ShieldCheck className="mr-1 h-3 w-3" />
                    Passed
                  </Badge>
                ) : (
                  <Badge variant="destructive" className="text-[9px]">
                    <XCircle className="mr-1 h-3 w-3" />
                    {gate.violations.length} blocking
                  </Badge>
                )}
                <span className="text-[10px] text-gray-500">
                  {gate.warnings.length} warning{gate.warnings.length === 1 ? "" : "s"}
                </span>
              </div>
              {/* Three states, never two: a skipped check is never green. */}
              <p className="text-[10px] text-gray-600">
                Syntax check:{" "}
                <span
                  className={cn(
                    "font-semibold",
                    gate.syntax_check === "passed"
                      ? "text-emerald-700"
                      : gate.syntax_check === "failed"
                        ? "text-red-700"
                        : "text-gray-500",
                  )}
                >
                  {gate.syntax_check}
                </span>
                {gate.syntax_check === "skipped" ? (
                  <span className="ml-1 text-gray-400">
                    — {gate.syntax_check_detail ?? "the check did not run"}
                  </span>
                ) : null}
              </p>
              {gate.violations.map((v, i) => (
                <p key={i} className="text-[10px] text-red-700">
                  <span className="font-semibold">{v.code}</span>: {v.message}
                </p>
              ))}
              {gate.warnings.slice(0, 5).map((w, i) => (
                <p key={i} className="text-[10px] text-amber-700">
                  <span className="font-semibold">{w.code}</span>: {w.message}
                </p>
              ))}
            </div>
          )}
        </Panel>

        <Panel
          title="Dry run"
          action={
            <Button
              size="sm"
              className="h-6 text-[10px]"
              disabled={running || runnerBlocked}
              title={runnerBlocked ? runner?.detail : undefined}
              onClick={() => void handleDryRun()}
            >
              <Play className={cn("mr-1 h-3 w-3", running && "animate-pulse")} />
              Run now
            </Button>
          }
        >
          {runnerBlocked ? (
            <div className="flex items-start gap-1.5 rounded border border-amber-200 bg-amber-50 p-2 text-[10px] text-amber-900">
              <AlertTriangle className="mt-0.5 h-3 w-3 shrink-0" />
              {/* The runner's real reason, verbatim. */}
              <span>{runner?.detail}</span>
            </div>
          ) : null}

          {outcome ? (
            <div className="mt-1.5 space-y-1">
              <p className="text-[10px] text-gray-600">
                run_status <span className="font-semibold">{outcome.run_status}</span> · exit{" "}
                {outcome.exit_code ?? "—"} · {outcome.duration_seconds?.toFixed(2) ?? "—"}s ·{" "}
                {outcome.runner ?? "—"}
              </p>
              {outcome.results.map((r) => (
                <div key={`${r.id}-${r.test_name}`} className="rounded border border-gray-100 p-1.5">
                  <div className="flex items-center justify-between gap-2">
                    <span className="truncate text-[11px] text-gray-700">{r.test_name}</span>
                    <StatusPill status={r.status} />
                  </div>
                  {r.error_message ? (
                    <p className="mt-0.5 text-[10px] text-red-700">{r.error_message}</p>
                  ) : null}
                  {/* Evidence links only when the run genuinely produced them. */}
                  {r.screenshot_url || r.video_url || r.trace_path ? (
                    <p className="mt-0.5 text-[10px] text-gray-500">
                      {[r.screenshot_url && "screenshot", r.video_url && "video", r.trace_path && "trace"]
                        .filter(Boolean)
                        .join(" · ")}
                    </p>
                  ) : null}
                </div>
              ))}
            </div>
          ) : history.length > 0 ? (
            <ul className="mt-1 space-y-1">
              {history.slice(0, 6).map((r) => (
                <li key={r.id} className="flex items-center justify-between gap-2">
                  <span className="truncate text-[11px] text-gray-600">{r.test_name}</span>
                  <StatusPill status={r.status} />
                </li>
              ))}
            </ul>
          ) : (
            <p className="mt-1 text-[11px] text-gray-400">
              This asset has never been executed. A passing dry run is required before it can be
              AI-approved.
            </p>
          )}
        </Panel>
      </div>
    </div>
  );
}
