"""Bridges the studio's test data needs into the shared Test Data module.

Requirement 4 in two halves:

  what the agent CAN manage  becomes a real row in the platform's `test_data`
                             table, so it appears in the Test Data module and
                             application users manage it there like any other
                             record. No parallel store.
  what the agent CANNOT      leaves `test_data_required` true with
                             `test_data_status='needs_user_action'`, which the
                             grid surfaces and approval refuses to pass.

Only `resolution == "agent_generated"` items become records: those are ones
the agent produced a concrete, synthetic value for. An "existing_record" or
"user_required" item has no value to store, and writing an empty placeholder
row would put a record in the Test Data module that looks provisioned and is
not.
"""
from __future__ import annotations

import logging
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from app.schemas.test_data import TestDataCreate
from app.services import test_data_service

logger = logging.getLogger(__name__)

AGENT_RESOLVABLE = "agent_generated"
NEEDS_HUMAN = {"existing_record", "user_required"}


def summarize(requirements: list[dict[str, Any]]) -> tuple[bool, str, str | None]:
    """Reduce a test case's data requirements to (required, status, notes)."""
    if not requirements:
        return False, "not_required", None

    outstanding = [
        req for req in requirements if str(req.get("resolution")) in NEEDS_HUMAN
    ]
    if outstanding:
        keys = ", ".join(str(req.get("key")) for req in outstanding)
        return (
            True,
            "needs_user_action",
            f"A human must provide test data before this test case can be approved: {keys}",
        )
    return False, "agent_provided", None


async def materialize(
    db: AsyncSession,
    *,
    project_id: int,
    user_id: int,
    test_case_display_id: str,
    test_case_title: str,
    requirements: list[dict[str, Any]],
    environment: str | None = None,
) -> tuple[list[int], list[dict[str, Any]]]:
    """Create shared Test Data rows for the agent-resolvable requirements.

    Returns (created test_data ids, requirements annotated with those ids).
    """
    annotated = [dict(req) for req in requirements]
    resolvable = [
        req for req in annotated if str(req.get("resolution")) == AGENT_RESOLVABLE
    ]
    if not resolvable:
        return [], annotated

    payload: dict[str, Any] = {}
    sensitive_fields: list[str] = []
    for req in resolvable:
        key = str(req.get("key") or "").strip()
        if not key:
            continue
        payload[key] = req.get("example_value")
        if req.get("sensitive"):
            sensitive_fields.append(key)

    if not payload:
        return [], annotated

    # One record per test case rather than one per key: the values are only
    # meaningful together (a username without its matching password provisions
    # nothing), and the Test Data module's reserve/consume lifecycle operates
    # on a record, so splitting them would make a test case's data
    # individually reservable and collectively meaningless.
    #
    # Created through test_data_service rather than by constructing a TestData
    # row here. That service sets the lifecycle columns the schema requires
    # (masking_status, reservation_status, quality_status and the rest, all NOT
    # NULL), allocates the TD-#### display id and runs the quality check — so
    # a studio-created record is indistinguishable from one a user made. Doing
    # it by hand skipped those columns and the insert failed on the first
    # record the agent actually generated.
    item = await test_data_service.create_test_data(
        db,
        project_id=project_id,
        body=TestDataCreate(
            name=f"{test_case_display_id} - automation test data",
            description=(
                f"Generated by the Test Automation Studio for "
                f"{test_case_display_id}: {test_case_title}"
            )[:1000],
            data_type="Automation",
            source_type="ai_generated",
            environment=environment,
            data_payload_json=payload,
            sensitive_fields_json=sensitive_fields,
            contains_pii=bool(sensitive_fields),
            privacy_level="confidential" if sensitive_fields else "internal",
            notes=(
                "Synthetic values produced during test case refinement. Review and approve in "
                "the Test Data module before using them against a real environment."
            ),
            tags=["test-automation-studio", test_case_display_id],
        ),
        user_id=user_id,
    )

    for req in annotated:
        if str(req.get("resolution")) == AGENT_RESOLVABLE:
            req["test_data_id"] = item.id

    return [item.id], annotated
