# GENERATED BY nxtQA Script Compiler — DO NOT EDIT DIRECTLY
# Contract Version: 1.0
# Compiler Version: 1.0.0
# Test Case: TC-0006
# Requirement: REQ-0010
# Environment Profile: SIT
# Script Type: pytest-python
"""TC-0006 — Order creation API returns a confirmed order with a ledger entry."""
import os

import httpx
import pytest

BASE_URL = os.environ["BASE_URL"]


@pytest.fixture
def order_payload():
    # Test data bound from the platform's Test Data module — never a
    # hardcoded literal in the committed script.
    return {
        "product_sku": os.environ["TEST_PRODUCT_SKU"],
        "customer_id": os.environ["TEST_CUSTOMER_ID"],
    }


def test_order_creation_confirmed_via_api_and_ledger(order_payload):
    # Arrange — order_payload fixture

    # Act
    response = httpx.post(f"{BASE_URL}/api/orders", json=order_payload, timeout=30)

    # Assert
    assert response.status_code == 201
    order = response.json()
    assert order["status"] == "created"

    ledger_response = httpx.get(f"{BASE_URL}/api/billing/ledger", params={"order_id": order["id"]}, timeout=30)
    assert ledger_response.status_code == 200
    assert ledger_response.json()["entries"], "Expected a ledger entry for the new order"

    # Evidence
    print(f"created-order-id={order['id']}")

    # Cleanup — cancel the order so it doesn't pollute downstream regression data
    httpx.post(f"{BASE_URL}/api/orders/{order['id']}/cancel", timeout=30)
